### ISSUE TITLE
Create post in proposal discussion

### ISSUE THREAD

**Issue by DevNikita16** [Joystream/pioneer#1427]

**Comment by p-sad** [comment]
Proposal discussion posts are a different type from forum posts in the schema, their fields are a bit different and not everything works with the current components. Both types could be made more generic in the frontend (e.g. by chopping off the `PostStatus`/`ProposalDiscussionPostStatus` prefix) but I'm not yet sure if this can be done to the full extent. This would mean we would be able to continue using the same components.
One thing that would need to be accounted for then is the edit history - these are two separate events/GQL types and a different query needs to be used, which would need to be handled by displaying a different component upon clicking the link.
Same will probably be true for a "reply to a post"/edit/delete options, as proposal discussion posts use a different set of extrinsics. Additionally, "reply to a post" is probably governed by thread mode in proposal discussion, so that would need to be a factor in display logic too.
