### ISSUE TITLE
Expand Pioneer 2.0 developer documentation

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1474]
The goal of this issue is to gather essential knowledge about the Pioneer 2.0 project in terms of:

*   application architecture
*   dependencies
*   development tools
*   deployment process

In this regard, we should improve & expand the existing documentation of the project. This should be in a form of well-structured `*.md` files that are linked together, where the main entry point is `README.md` file.

The focus of such documentation should cover:

*   [x] development setup
*   [x] starting working on the project
*   [x] automated tests vs storybook
*   [x] any tips & tricks helpful to debug problems (e.g. using polkadot apps with testnet)
*   [x] working with mocks & live network
*   [x] a brief listing of architectural decisions that were made according to the tools & libraries used
*   [x] common development tasks
*   [x] how to expand existing features like adding proposal handling, adding activities, etc
*   [x] development vs build versions (e.g. what should be visible in both)
*   [x] fix links to code

---

Documentation preview on `docs` branch: https://github.com/Joystream/pioneer/tree/docs

**Comment by thesan** [comment]
@jodator what comes to my mind now is the various common errors which can happen when mocking data, eg:
- Mirage: The xxx model has multiple possible inverse associations for the xxx.xxx association.
- The error when an object is passed as an attribute in the seeding process instead of creating a model...
- Or even, no resolver being found when q new query hasn't been added to the Mirage server
