### ISSUE TITLE
Table memberships specified more than once

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1752]
Some filter combinations, mostly liftetime + proposer, like below:

![](https://user-images.githubusercontent.com/247363/141097243-cbea3e72-18d7-4bfa-9932-7a4fa3042617.png)

Returns an error on testnet:

![](https://user-images.githubusercontent.com/247363/141097471-7969da93-c687-4112-8aba-6ef5db67cbac.png)

This may be either:

*   error in past proposal filters
*   error in Hydra implemention

Also, check other filters, like:

*   archived forum categories

**Comment by p-sad** [comment]
As it turns out, the `table specified more than once` error was caused by the incorrect use of the `OR` clause, in conjunction with how SQL queries for the underlying database are generated from GQL queries in Hydra.

If a query for an object contains a filter input for a related object ( e.g. `where: { member: { id_eq: $id } }`, a left join for that object's table is generated. This works with normal queries because each joined table receives an alias based on its field name. So if e.g. we have a `Payment` entity that has two fields of type `Membership`, one of them called `payer` and the other `receiver`, the query will left join with the `membership` table twice, but this will not be a problem since the first join will be aliased as `payer` and the second as `receiver`.

Here, each `OR` clause contained an input for the `membership` field, which resulted in three left joins, all named after the same field - which in turn resulted in a name collision.
```sql
SELECT "proposal"."id" AS "proposal_id", "proposal"."created_at" AS [...]
  FROM "proposal" "proposal"
  LEFT JOIN "membership" "membership" ON "proposal"."creator_id" = "membership"."id"  
  LEFT JOIN "membership" "membership" ON "proposal"."creator_id" = "membership"."id"  
  LEFT JOIN "membership" "membership" ON "proposal"."creator_id" = "membership"."id" 
  WHERE [...]
```

This was a result of my misunderstanding of the `OR` field - a where input like `{ field1: 10, OR: [{ field2: 11 }]` doesn't mean "find an object that has a number 10 in field1 or an object that has a number 11 in field2". Instead, it means "find an object that has 10 in field1 AND 11 in field2". Instead, the `OR` field should be used like this:
```gql
where: {
  ...commonWhereParameters
  OR: [{ ...firstSetOfParameters }, { ...secondSetOfParameters }]
}
```
In which case, we're looking for objects that match (commonWhereParameters AND firstSetOfParameters) OR (commonWhereParameters AND secondSetOfParameters)

**Comment by jodator** [comment]
Very nice summary :+1:
