### ISSUE TITLE
Validate proper total budget stat calculation

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1757]
@DevNikita16 There's an [update](https://www.figma.com/file/Z3KcRoAll3JGEY622o0iZu?node-id=185:28845#120651584) on what that value should be:

> I believe this was of spending. So take total spending, and then figure out what the maximum possible spending could be over the given period, and find the percentage of the former w.r.t. the latter.

Please check if we calculate this as described.

**Comment by dmtrjsg** [comment]
@Qcza can you pls check in the code and add here as comment the formula used in calculating this figure?

Needs to be: **Total Spent By Working Group as % of Total budget of Council per current period.** 

Total (council) budget is defined for period of council with some periodic (e.g. daily) allowance to allocate for working groups. This info is kept on the chain for councils.

**Comment by Qcza** [comment]
Current formula is
```
workingGroup.budget.muln(100).div(totalBudget)
```
So here we're just checking what part of the total budget is the working group's budget.

It makes sense because the current implementation of this view is slightly different from the wireframe. Right now we don't have "total spent" and "total dept" columns, we have the budget column instead, so the discussion is irrelevant to the current implementation.

![Zrzut ekranu 2022-01-12 o 09 43 38](https://user-images.githubusercontent.com/7772094/149094607-6afa25b0-8945-407a-a2fb-8c451552c34a.png)

**Comment by dmtrjsg** [comment]
I think its ok like this, thank you for flagging!
