### ISSUE TITLE
External resources for memberships 

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#1977]
# Scope

- [ ] Update membership creation
- [ ] Clicking on SM source icon extends input
- [ ] Placeholder text is customised for each media type
- [ ] Editing (two sections, additional one is "Social Media"
- [ ] Display (membership details drawer) to support such resources.

# Context

Content directory will support adding decorations to the metadata standard for each entity, to support adding one or more of the following https://github.com/Joystream/joystream/issues/2813

- Email
- Handle on one among a standardized, and easily extensible, set of services: the following seem sufficient for starters

discord/tlgrm/keybase/github
+
  - Twitter
  - Telegram
  - Discord
  - Facebook
  - YouTube
  - Matrix
  - IRC
  - Wechat
  - WhatsApp
- Raw link

⚠️  We need to make it non-demanding as this is bordeline self-doxxing if we are asking for everything .

# Dependencies

https://github.com/Joystream/joystream/issues/2813

**Comment by MattAugustynowicz** [comment]
Starting from the very beginning, let's change our weird toggle to a simple checkbox that will communicate if we have received an invitation from another member.

The second thing that has changed is to add headers to the sections (Referral Program, Essentials, Social Profiles). This will help us structure the whole modal and separate the content visually.

[👉 Figma Link - Default Membership](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8631%3A262482)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/fa48cfdc-3897-4305-b358-e5f475243644)

Now about External resources for memberships, I propose to add this in the form of boxes instead of immediately observable inputs, which will take up a lot of space. In this case, the user will instantly see the complete list of platforms, and it will not be overwhelming. After clicking on a given tile, an active placeholder appears, where we can immediately enter our username. The tile that we clicked on disappears from the list, so it will be possible to have only inputs and no tiles. The placeholder can also be removed using the "x" icon on the right side of the input, this will return our tile to the original list. 

[👉 Figma Link - Membership States](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8631%3A263663)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/a0065a9e-9649-4601-af20-e1c27ac86fdc)

When it comes to editing this data, without going crazy, let's add simple text information in the membership window, and after clicking edit, let's similarly display the tiles and placeholders I wrote about above

[👉 Figma Link - Membership Preview](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=2596%3A115078)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/a14e220a-f659-46c8-8574-7d229d8575d3)

**Comment by dmtrjsg** [comment]
Reviewed:

need more clarity to showcase the Showing and Editing info on Member profile views.

**Comment by dmtrjsg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pioneer-603cf0017ea5c9001b428eba/issues/Joystream/pioneer/1977?planning-poker) with ZenHub @RafalPloszka @stepien4soft @thesan @WRadoslaw

**Comment by WRadoslaw** [comment]
@dmtrjsg @MattAugustynowicz  hey, WDYT about keeping tiles above new inputs? That way user can just quick select desired socials and then fill input below. RN when you want to add multiple socials and then fill them out it's a pain since with each input they get pushed down

**Comment by MattAugustynowicz** [comment]
> @dmtrjsg @MattAugustynowicz hey, WDYT about keeping tiles above new inputs? That way user can just quick select desired socials and then fill input below. RN when you want to add multiple socials and then fill them out it's a pain since with each input they get pushed down

@WRadoslaw Excellent point sir. Sure! Let us do as you say. Thank you 🙌

**Comment by dmtrjsg** [comment]
UPD:
Mokhtar merged and deployed https://github.com/Joystream/membership-faucet/pull/16

#16 :sa: External resources on register route
Comments: <https://github.com/[Joystream/membership-faucet](https://github.com/Joystream/membership-faucet)|Joystream/membership-faucet>Joystream/membership-faucet | Jul 15th | Added by [GitHub](https://joystreamworkspace.slack.com/services/B039R2P5FD4)


QN at [query.joystream.org](http://query.joystream.org/) pointed at synced node with the mappings updated from https://github.com/Joystream/joystream/pull/3862

[#3862 Qn map metadata for external resources for members](https://github.com/Joystream/joystream/pull/3862)
Closes [#2813](https://github.com/Joystream/joystream/issues/2813)

<https://github.com/[Joystream/joystream](https://github.com/Joystream/joystream)|Joystream/joystream>Joystream/joystream | Jun 7th | Added by [GitHub](https://joystreamworkspace.slack.com/services/B039R2P5FD4)
[3:37](https://joystreamworkspace.slack.com/archives/C039XD9HKKL/p1659105465778019)

ℹ️ .. this is rhodes testnet ofcourse

**Comment by dmtrjsg** [comment]
Creation works ✅ 
Editing was breaking QN 🚫 
Faucet to be tested ➡️

**Comment by dmtrjsg** [comment]
Env where Faucet and QN are updated with External Memberships: ihttps://54.172.204.195.nip.io/network/config.json

**Comment by dmtrjsg** [comment]
@WRadoslaw deleting case spotted malfunctioning..

**Comment by dmtrjsg** [comment]
@ivanturlakov ready to retest

**Comment by ivanturlakov** [comment]
✅ Retested on https://dao-git-carthage-joystream.vercel.app/#/network-config=https://3.92.226.32.nip.io/network/config.json

https://user-images.githubusercontent.com/46903215/192506875-c229c5e5-2d2d-4c11-908f-e78f959d591a.mov
