### ISSUE TITLE
Announce Work Entry

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2016]
**Context**

Working announces[ work entry](https://joystream.gitbook.io/joystream-handbook/subsystems/bounties#announce-work-entry) for bounty in [working stage. ](https://joystream.gitbook.io/joystream-handbook/subsystems/bounties#fund-bounty)

This is pretty much about locking a stake

**AC**
- [x] Worker can [announce work entry](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=248%3A136585)
- [x] Description is mandatory
- [ ] Submit custom/ full/half amount from stake acc (subject to minimum stake amount taken from bounty creation flow)
- [ ] All conditions and effects are met [link to handbook](https://joystream.gitbook.io/joystream-handbook/subsystems/bounties#announce-work-entry)
- [ ]  Metadata encoded
- [x] User cannot chose which Member ID to use (from drop down) to submit entry; but can choose staking account

**⛔  OOS**

- [ ] Description Field is removed - It is not supported by current chain ⚠️ remove from scope

**Comment by Qcza** [comment]
According to the current runtime code, we cannot edit the stake. It is always the same, based on the value set in the createBounty process.
Also, we cannot set the entry description. 

So as far as we don't want to update the runtime code, the UI design should be changed. We should remove the description field and block the possibility to edit the stake's amount. @dmtrjsg

**Comment by thesan** [comment]
@dmtrjsg I understand the work description as what is shown [on the work tabs](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=248%3A137680) but I don't really understand what is the entry description. I could just add a description field to the schema while waiting for the runtime, but if this field is not shown on the frontend it would be useless in the query nodes

**Comment by bedeho** [comment]
> Staking amount for work entries set up in Bounties creation flow is not editable when user creates work entries for such bounty. Staking amount on Work entry is Read-only

Correct, also visible here in call to runtime for announcing entry: there is no way to specify amount
https://joystream.gitbook.io/joystream-handbook/subsystems/bounties#announce-work-entry

> If staking amount is disabled (toggle = false), the Staking amount on the work entry is set to 0 and not editable?

I assume this is during bounty creation this disabling is occurring? This is actually in general not a great pattern, because the runtime may will in general require all bounties to have a minimal stake amount `MinWorkEntrantStake` from the handbook, likely greater than 0. Moreover, even if it was 0, the announcement of an entry would _still_ require supplying an account regardless!

https://github.com/Joystream/joystream/blob/bounty/runtime-modules/bounty/src/lib.rs#L964

This is actually pretty narly devUX, perhaps even warrants updating the runtime to make it optional in the extrinsic signature.

So in the end, at least, the entry announcer _has to_ provide a valid staking account, possibly with 0 balance, even if the bounty required 0 stake, ... but, the bounty is likely to require some >0 hard coded minimum level anyway.

Hope that was clear.

> I understand the work description as what is shown on the work tabs but I don't really understand what is the entry description. I could just add a description field to the schema while waiting for the runtime, but if this field is not shown on the frontend it would be useless in the query nodes

Where is the entry description referenced? I could see a use for it hypothetically, but if its not used in the front-end, then you can just drop it for now.

**Comment by dmtrjsg** [comment]
Thanks for the answers @bedeho  

Pls see [Figma link for Announce Work Entry Modal](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=248%3A136585) for context. It seems like the consequence of designing _work_ modal and re-using for _work entry_ without adjustments.

I've checked [the handbook section for Announcing work entry](https://joystream.gitbook.io/joystream-handbook/subsystems/bounties#announce-work-entry) and it mentions metadata. Can this be the source of confusion?

**✅  Actions**

- [ ] Remove the toggle from Bounty staking in [working period details](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=248%3A109592)
- [ ] Check if MinEntrantStake can be 0. 
-- if it can be 0, happy days :) 
-- If it cannot, set field validation to >0 with error message "MinEntrantStake has to be greater than zero."
and update [handbook ](https://joystream.gitbook.io/joystream-handbook/subsystems/bounties#announce-work-entry)for this condition.
- [ ] [update handbook ](https://joystream.gitbook.io/joystream-handbook/subsystems/bounties#announce-work-entry)wrt Work entry description/ meta (❓ tbc, see below)

<img width="725" alt="Screenshot 2022-01-13 at 16 27 03" src="https://user-images.githubusercontent.com/93924525/149370267-213404e7-c8ea-4016-819a-2135d8f79b73.png">
