### ISSUE TITLE
Insufficient explanation: Stake requirements for proposals

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2271]
This window shows when trying to create a proposal that requires `50,000 JOY` as stake:
![image](https://user-images.githubusercontent.com/50830161/154818378-11978a8d-7bd5-4278-9d3e-c29ad44e98d1.png)

This is confusing for a number of reasons
- It shows the `root account` and the stake requirements--which is highly confusing
- It doesn't explain that the `root account` cannot be used for staking and that a secondary account needs to be used for this purpose

This page would benefit from a better explanation of why the particular accounts that do exceed the "free balance" requirement will not work in this scenario.

**Comment by traumschule** [comment]
Convincing. The `move funds` heading could be expanded with a tooltip or just an additional sentence:
> Move funds from your root account to a _staking account_  [handbook link]

**Comment by mochet** [comment]
> Convincing. The `move funds` heading could be expanded with a tooltip or just an additional sentence:
> 
> > Move funds from your root account to a _staking account_  [handbook link]

The whole staking system has changed ):

**Comment by bwhm** [comment]
Hey @mochet and @traumschule 

> This window shows when trying to create a proposal that requires `50,000` JOY as stake:
Are you sure? Pioneer says it's `100,000`JOY.

What's happening here, is that Pioneer is telling you two things at once (not sure if there was a window before, but I assume not)
1. Your membership `root` account can't be used for this purpose, presumably due to your membership having used that for a "rivalrous" stake.
2. These are the accounts you have (with tokens) that you can transfer too/from.

How this is phrased is probably not ideal.

> It shows the root account and the stake requirements--which is highly confusing
The `root account` is there to show which membership you are using. I guess it would be beneficial if that was explained as:
"Member `<ID>` root account"

> It doesn't explain that the root account cannot be used for staking and that a secondary account needs to be used for this purpose
True, this is implied, but not spelled out sufficiently for a new user.

**Comment by dmtrjsg** [comment]
@bwhm @mochet  this issue was addressed here > - #2219  and locks info is being also addressed here > - #1556
