### ISSUE TITLE
Casting vote: add validation for staking amount vs selected account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2361]
- [ ] Can we add field validation on voting: acc balance cannot be lower than staking?
- [ ] Ideally to do it right at the point of input,
- [ ] There seems to be no validation on the sign transaction either..

Resulting in casting vote, caught a transaction error:

https://polkadot.js.org/apps/?rpc=wss://3.95.67.177.nip.io/ws-rpc#/explorer/query/0xc465d9d332261eefea3c57924987bf6cb5a1bd885084415ff29c6211f82f381a

![Screenshot 2022-02-28 at 16.18.40.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/f3c9e26c-2e9a-4605-b134-88f75cf49cfd)

**Comment by dmtrjsg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pioneer-603cf0017ea5c9001b428eba/issues/Joystream/pioneer/2361?planning-poker) with ZenHub @RafalPloszka @stepien4soft @thesan @WRadoslaw

**Comment by dmtrjsg** [comment]
@WRadoslaw  @stepien4soft can you pls remind me why we send this to design as opposed to just applying the same validation as we have done for proposals and bounties?

**Comment by traumschule** [comment]
Just to update since some things changed since Feb, not much however wrt to this issue.

## Current: single voting
- Currently voting requires me to know my account balances and keys.
- The `Vote for council` modal usually hides these because i voted in previous election => staked
- I paste the key into the select field and the account becomes visible. I could also paste someone else's key which is shown as _Unsaved account_ but then the transaction would obviously fail. => show all my available keys
- I set the correct amount manually because there is no indication of total or available balance. => a [slider](https://mui.com/material-ui/react-slider/) to select fraction of total balance might be best for single voting.

## Ideal: multi-voting
Alternatively an ideal way to vote would allow token holders to vote for multiple candidates in one go following [NPoS](https://research.web3.foundation/en/latest/polkadot/NPoS/1.%20Overview.html) election logic:
![NPoS Election](https://research.web3.foundation/en/latest/_images/NPoS_3.png)
- User defines vote targets for each candidate via text input
- Candidates are automatically sorted based on input
- Pioneer would be smart enough to verify inputs and handle all transactions:
- **Example**: User sets 60M on A and 40M on B. Available accounts are 4x 20M and some smaller stakes. Pioneer uses three stakes on A and one on B + smaller balances from other accounts to reach target of 40.

**Comment by traumschule** [comment]
To summarize the video:
- the user is able to insert more than available balance without validation error
- it is unknown how much the person staked / locked => these can be used for voting and should be visible

**Comment by dmtrjsg** [comment]
@ivanturlakov can you pls raise this case as a separate issue, the remainder is left only cosmetic treatment. We need to show the validation error underneath the account selector "Insufficient funds".

This one goes to production as is as not blocking.
