### ISSUE TITLE
[USERSNAP] When trying to slash a worker, the amount injected is always 0

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2381]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/32
**Fields**:

* Houston, we have a problem.: When trying to slash a worker, the amount injected is always 0
* Give us some details: I tried with both 1 and 111 for content Lead
* 
* 
* Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f13f8f9d-cd5d-4b76-a083-1bd1592fbd6a-annotated_4f765601-3d00-4d7a-8f6d-aeedd0be28e3.png?etag=45802a39c4050d392074e1733cc55a29)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f13f8f9d-cd5d-4b76-a083-1bd1592fbd6a-annotated_4f765601-3d00-4d7a-8f6d-aeedd0be28e3.png?etag=45802a39c4050d392074e1733cc55a29)_

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 2560x1304
**[Open #39 in Usersnap](https://app.usersnap.com/l/feedback/78a3820e-3a74-430f-8500-354291d6b20a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201903897210060) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
![Screen Shot 2022-03-02 at 00 26 48](https://user-images.githubusercontent.com/35237943/156266317-9f53c14a-bdf7-4db1-b0bf-2e58f3889175.png)

**Comment by dmtrjsg** [comment]
There was a conversation that slashing amount always slashes full stake (for bounties), and there was no input on it at all.. @thesan  do you know if in case of Proposal  to slash wgl this is handled differently?

**Comment by thesan** [comment]
For bounties it was a runtime limitation but it shouldn't be the case for the proposals.

It's probably another case of the value getting lost when the specific parameters are encoded. I think we should add automated test on all of this proposals types.

**Comment by dmtrjsg** [comment]
Caused by similar problem of the proposal specific parameters..

**Comment by WRadoslaw** [comment]
About params:
- Leader ID is always 0 -> because factory passes to transaction leader `runtimeId` which is `0` for all, is it desired behaviour or can I change it to normal ID?
- Slash amount is always 0 -> some1 made typo and passed wrong key which defaulted to 0

After fixing both polkadot app and pioneer crashes on details of created proposal. Polkadot app can be fixed by defs.json update [this one](https://raw.githubusercontent.com/Joystream/joystream/olympia-playground/types/augment/all/defs.json) 

Im suspicious about amount after creation:
My last input in app was `2121` 

![image](https://user-images.githubusercontent.com/92513933/156519498-3b6b1f50-d51e-4b0a-9954-50d569cc0f8b.png)

But it results like that in polkadot apps:

![image](https://user-images.githubusercontent.com/92513933/156519578-bab9ecb8-a123-400a-8825-eb786f95fc34.png)

Not sure if that's desired outcome, so I wanted to raise it. @thesan
