### ISSUE TITLE
Design consideration

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2540]
Using comma as a thousand separator, eg. `50,000`, isn't common across the world. Some use `50 000` and the comma is used as the decimal point.

Considering we already have "large" amounts in play, and there is no way to know what the future holds in that regards, it may be preferable to use the prefix, like Substrate/Polkadot is doing, and show `50k` in pioneer. The downside is that you may not know the exact number, without making it "long" again with `50.001k` or `50,001k` depending on preferences.

That could be solved by:
1. Settings - allowing users to choose between formats to display the number `50001+4/10` as one of:
   - `50k`
   - `50.0k`
   - `50,0k`
   - `50 001,4`
   - `50 001.4`
   - `50.001,4`
   - `50001,4`
   - `50,001.4`
   - `50001.4`
   - `5.00014*10^4`
   - `5,00014*10^4`
   - etc?
  2. Default to some "common" standard, but if you hover over the number, it displays the full amount as `50001.4`
  3. Other

ref https://github.com/Joystream/pioneer/issues/2539

**Comment by traumschule** [comment]
Thanks! This bugged me a while. My ideas/wishes for defaults:
- Display `209,141.000 JOY` as `209 141 JOY` or `209.141 kJOY`, `200.0000 MJOY` as `200 MJOY`, 2,940,700,000 as `2.9407 BJOY` like on pioneer1 `/#/explorer` (using [FormatBalance.tsx](https://github.com/polkadot-js/apps/blob/master/packages/react-query/src/FormatBalance.tsx))
- Copy&Paste should pick the exact value as shown in tooltip with . and without digit grouping or currency unit to be usable in calculators for example. Also for block numbers (4905120 instead of 4,905,120)!
- Smart hide fraction when 0

> Default to some "common" standard, but if you hover over the number, it displays the full amount as 50001.4

++1

> Using comma as a thousand separator, eg. 50,000, isn't common across the world. Some use 50 000 and the comma is used as the decimal point.

[Germans use `,` to indicate fractions and space or `.` as separator every three digits, English has `.` for fractions.](https://language-boutique.com/lost-in-translation-full-reader/writing-numbers-points-or-commas.html) -> Change together with language setting.

**Comment by bedeho** [comment]
Seems to be covered by this https://github.com/Joystream/pioneer/issues/2531
