### ISSUE TITLE
Cancelling bounty  

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2637]
#### Context

Creator cancels bounty, transaction confirmation modal is displayed, signed.. [loom](https://user-images.githubusercontent.com/80429191/165798031-b582289a-0e90-4d52-9914-f6db71bb9fef.mp4)

**Scope**
- [ ] Fix the sign-in modal copies
- [ ] Redirect to the bounties list after the transaction finishes
- [ ] Replace the see my bounty button on the confirm modal to "Back to bounties"

___
#### Expected

- [x] QN refetched in the back, bounty details page shows in cancelled state  and no further actions possible ⚠️ Depends on QN 
- [ ] Transaction confirmation modal shown with CTA "OK acknowledged".  
- [ ] When cta clicked - modal closes

+

- [x] Terminated bounties show in past bounties

#### Actual
- [ ] Transaction confirmation modal shows. ✔️ 
- [x] QN refetched 🚫  
- [ ] CTA View bounties ✔️ 
- [x] Page refreshed manually results in eternally loading blank page 🚫 

ℹ️  **More Details**
https://www.loom.com/share/cf59422fdcb64932a9e7bcc556f8006a

**Comment by polikosi** [comment]
Expected:
 1. QN refetched in the back, bounty details page shows in cancelled state and no further actions possible
 2. Transaction confirmation modal shown with CTA "OK acknowledged".
 3. When cta clicked - modal closes
 4. Terminated bounties show in past bounties

Actual result:
 1. Modal display of transaction confirmation with incorrect name
 2. CTA inactive (attached screen)
 3. After closing the window through the cross I see a blank screen and endless loading, because that url no longer exists

![Cancelling bounty transaction #2637](https://user-images.githubusercontent.com/80429191/165797999-21a213c3-2db1-4d43-ac7e-7ba3067ccb7a.jpg)

https://user-images.githubusercontent.com/80429191/165798031-b582289a-0e90-4d52-9914-f6db71bb9fef.mp4

**Comment by talentdev0807** [comment]
@talentdev0807

**Comment by polikosi** [comment]
Verified on staging. Everything works as expected. Test evidence below:

https://user-images.githubusercontent.com/80429191/171918971-e1cbc216-60fd-4972-83f4-1924fe45e92d.mp4
