### ISSUE TITLE
Rivalrous locks should not impact voting for council

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2666]
The account in question has a council lock applied, indicated by an icon. This should not prevent user from using the same account for voting. Raising this as a bug.

![Screenshot 2022-03-24 at 14.25.02.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/5907ca8c-6d61-4e69-8475-8550fb370a54)

**Comment by thesan** [comment]
@dmtrjsg the screenshot shows a ["Council Candidate" lock](https://pioneer-2-storybook.vercel.app/?path=/story/accounts-accountlocks--default) (which is rivalrous). And from the amount of the minimum stake (25k) it looks like a proposal creation modal not a vote (where the minimum stake is 10k). In this case it would be the expected behavior.

Still I've tried to reproduce this with an account with a different rivalrous lock on the voting modal and (despite the selector filtering the wrong accounts by default) Pioneer doesn't prevent voting with accounts which have a rivalrous lock.
