### ISSUE TITLE
WG tooltips

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2681]
[ ] links to gitbook for each working group on hover
[ ] CTA to point to gitbook on working group description page

[Storage>](https://joystream.gitbook.io/testnet-workspace/system/storage)
[Content >](https://joystream.gitbook.io/testnet-workspace/system/content-directory)
[Builders>](https://joystream.gitbook.io/testnet-workspace/system/builders)
[Distribution>](https://joystream.gitbook.io/testnet-workspace/system/storage#distributor)
[Marketing>](https://joystream.gitbook.io/testnet-workspace/system/marketers)
[Human Resources](https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/human-resources-score)
[Membership>](https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/human-resources-score)

**Comment by bwhm** [comment]
I _think_ the design was referring to the "blog" module, so that the group could change this with a TX.

My two cents:
- Add a placeholder text: "This page hasn't been filled out by Storage Lead (yet). In the meantime, here is a link to [gitbook](https://joystream.gitbook.io/testnet-workspace/system/storage) and the groups [notion board](https://grizzled-corleggy-af8.notion.site/Storage-9dc5a16444934dc4bda08b596bc15375)
- We then let the group Leads make a PR with the text, (probably better with an issue in markdown)

Makes sense?

The other notion boards: https://grizzled-corleggy-af8.notion.site/joystream/Joystream-Workspace-1175fcb1cc644fdb874558181fd2dbee

**Comment by traumschule** [comment]
Updated link: https://joystream.notion.site/joystream/Joystream-Workspace-1175fcb1cc644fdb874558181fd2dbee
