### ISSUE TITLE
[USERSNAP] Forum post readability

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2734]
+ comment Medium is a good benchmark for posts readability

**Taken at**: https://dao.joystream.org/#/forum/thread/17
**Fields**:
- Houston, we have a problem.: Forum post readability
- Give us some details: Make post text way bigger, its super inconvenient to read now.
- Small text on forum.
- Discord Handle: bedeho

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/baf7d468-d505-4ada-b36c-63f73ce38974-annotated_0a0b7918-ab08-421b-a3ea-07c52bcd73e6.png?etag=fa052e12310073f61b46a953303cdc81)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/baf7d468-d505-4ada-b36c-63f73ce38974-annotated_0a0b7918-ab08-421b-a3ea-07c52bcd73e6.png?etag=fa052e12310073f61b46a953303cdc81)*

**Browser**: Firefox 98 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1781x1173
**Labels**: bug-non-critical
**[Open #165 in Usersnap](https://app.usersnap.com/l/feedback/bf275534-53dc-45c7-a513-c60b6422adf8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by MattAugustynowicz** [comment]
I propose to change our texts upwards by one scale. That is paragraphs from 14px to 16px, and quoted texts from 12px to 14px. In addition to changing the size of the fonts, it will be essential to adjust the length of the rows. This significantly improves readability and helps us with the transition between one line and another. The rules say that 75 characters is the maximum per line, but our texts are not too long, so they can have up to 100 characters. 

[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8821%3A332556)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/9c9533b8-61f9-49ae-9ced-b9f1f1f66086)

**Comment by dmtrjsg** [comment]
From the linked ticket "..and it may be that contrast is not that good either. Compare for example readability of this page with a Medium post? It's night and day." 

Can we cook a version where text colour is black, maybe some padding needs to be reviewed (also see how this space on the righthandside of each post is "idle.." - worth exploring fixing this as well?

**Comment by MattAugustynowicz** [comment]
Alright, so let's change to another darker color from our palette, which is #404B5A. In terms of WCAG, we have triple-A here, so darker doesn't have to be. As for the right side, I don't find it problematic. We agreed globally in the project on some padding, so I think it's better to stay here with the ones that are so that it doesn't jump around on every page. I think that a forum is a place that can be improved, but in subsequent stages after solving other more problematic tasks within Pioneer, because this and the change I described earlier fix the problem of lack of readability completely.

👉 [Same link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8821%3A332556)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/dbce7d73-ac1d-4d4d-b3de-056e2de8b11f)

**Comment by dmtrjsg** [comment]
>As for the right side, I don't find it problematic. 
- What's the benefit of having so much white space on one side? is it worth a/b checking if we want to make the cards with posts a little more narrow and perhaps display indentation for the replies?

Readability is improved with font up, but overall It feels somewhat undercooked due to excessive line break spacing and white space on the right..

**Comment by MattAugustynowicz** [comment]
@dmtrjsg 
Sure, I understand the approach. I'll throw all forum-related tasks on the grill and let's cook this properly :)
