### ISSUE TITLE
Bounty Entry: multiple issues

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2739]
## Context

Originated in related issue: https://github.com/Joystream/joystream/issues/3526

It seems that if a user on submitting entry _manually pastes in an account address_ (instead of selecting from drop down) it allows to proceed to submission even  if an account is already bound to another member. 

This results in a failed transaction:

<img width="528" alt="Screenshot 2022-04-08 at 14 53 29" src="https://user-images.githubusercontent.com/93924525/162449998-651770fd-826b-4381-942f-8bab036f553a.png">

In one instance it used an address that the user _did not own/have in their wallet._

Reference videos:
* https://drive.google.com/file/d/12tRqKKuSq0unrO0ap8BeU4k0Bz7giyBk/view?usp=sharing
* https://drive.google.com/file/d/18ltYI4zHWPh3kf7KUMrKhrDDlDgrDt1S/view?usp=sharing
* https://drive.google.com/file/d/1pWnD1ohPRrpfzknz4Bf3ZMWqkhAqn580/view?usp=sharing

**Comment by mochet** [comment]
In the 3rd video provided, the staking account had a balance of `1001 JOY` and it was unbound, the binding requires locking `200 JOY` and the stake requirement was `1001 JOY` meaning it probably failed because only `800 JOY` remained after the relationship was created.

**Comment by mochet** [comment]
Another example: https://drive.google.com/file/d/1pq8vY_CqX28b-n1ia_4EphtO9Ofp8FKw/view?usp=sharing

In this scenario, the user selects a different account at 01:12 for `fees`--this results in Pioneer trying to sign the transaction using the fee account which isn't associated with the `member ID` and results in this error: https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944/#/explorer/query/0xb1f180dbd3e54c9e2629dd51f974345308f9fe57e4d8b1934d9588fb5fa9dfb7

**Comment by mochet** [comment]
Another example: https://drive.google.com/file/d/1KVFp1uJw4fcfxyAAk2PtgJYPMbyt-9vU/view?usp=sharing

In this scenario, the "fee" seems to be using `cherry value` instead of `stake value`
- Cherry value is `1000 tJOY`
- Stake value is `5000 tJOY`
- Account has a balance of `1500 tJOY`
- Submitting work fails because it seems to be using `Cherry value` instead of `Stake value`

![image](https://user-images.githubusercontent.com/50830161/160932672-ad2ddb56-a0f2-417f-9254-1a8e6cab949b.png)
![image](https://user-images.githubusercontent.com/50830161/160932542-7341883c-3a22-4afa-a6da-bd522a8d035c.png)

**Comment by dmtrjsg** [comment]
1st - add validation to copypasted accounts (not just the selection form drop down) for locks
2nd - check for sufficient balance
3rd video provided, the staking account had a balance of 1001 JOY and it was unbound, the binding requires locking 200 JOY and the stake requirement was 1001 JOY meaning it probably failed because only 800 JOY remained after the relationship was created.

**Comment by mochet** [comment]
@dmtrjsg 
There was a 4th issue I think you may have missed: https://github.com/Joystream/pioneer/issues/2739#issuecomment-1083619179
Specifically, when submitting the `fees` it allows the user to select a different account which results in transaction failure. I am guessing it shouldn't be selectable?

**Comment by dmtrjsg** [comment]
@WRadoslaw  had a quick test, few questions mate:

1. What's the underlying logic of implementation of "Might be bound to another member". Are we using this message as a loading state, while doing acc validation? If so, we should use a loading state of selector component for for this.

<img width="439" alt="Screenshot 2022-04-08 at 15 02 27" src="https://user-images.githubusercontent.com/93924525/162452469-c5ad9308-b8d4-442a-bc7a-713b51e7b902.png">

- let's update to 'validating account" small copy and not highlight as input error.

2. Testing with a previously unregistered acc and hidden form browser, gave an error:
<img width="316" alt="Screenshot 2022-04-08 at 15 11 06" src="https://user-images.githubusercontent.com/93924525/162453369-8ef709f1-ffad-4e77-9ed3-a2a3755ba2b2.png">
Clicking on link pointed to > 
throw new Error(`web3FromAddress: Unable to find injected ${address}`);

- let's prevent from using accounts invisible from browser (disabled/hidden in the extension)?

3. Testing with a registered acc, bound the account successfully, but pre-populated Alice ROOT account, instead of newly bound role acc.

- let's use the newly bound acc from step 1 in signing the entry stake.
