### ISSUE TITLE
Additional columns for Members list

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2888]
## Context

please add columns to Members table for

who referred if any member
time when membership was created (bedeho: Give us some details: I would like to know at what point in time a given membership was created on the All Members table. ID is a proxy for order, but I would like to know time.)

![Screenshot 2022-04-22 at 12.22.12.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/421d0831-1f1d-44e3-a722-ef094603a640)

## Scope

1️⃣  Redesign as per figma: [👉 Figma Link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9825%3A387305)

As we do not have a lot of space to accommodate all the information, I propose to relocate the member ID  directly below the membership handle (as Dmitry rightly pointed out during the meeting, no one will sort the list by ID number). 

It is also not necessary to show council members as a separate field, since there are only a few of them for 4k+ members. So I think it would be a good idea to move this indicator as a check icon just after the user handle.

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/c8e4d113-50a6-4ec7-8f52-1c392debe46f)

2️⃣  Lock icons cosmetic fix

<img width="366" alt="Screenshot 2022-07-06 at 08 47 30" src="https://user-images.githubusercontent.com/93924525/177498363-b36c89aa-d248-497e-84b6-0cac6c9623d1.png">

**Comment by MattAugustynowicz** [comment]
[👉 Figma Link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9825%3A387305)

As we do not have a lot of space to accommodate all the information, I propose to relocate the member ID  directly below the membership handle (as Dmitry rightly pointed out during the meeting, no one will sort the list by ID number). 

It is also not necessary to show council members as a separate field, since there are only a few of them for 4k+ members. So I think it would be a good idea to move this indicator as a check icon just after the user handle.

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/c8e4d113-50a6-4ec7-8f52-1c392debe46f
)

**Comment by freakstatic** [comment]
@singulart please assign

**Comment by singulart** [comment]
> @freakstatic Could we also tackle the misplacement of the lock icons in this ticket?
> 
> Expected: Lock icons positioned underneath the balances, with a 5px vertical spacing between.
> 
> <img alt="Screenshot 2022-07-06 at 08 47 30" width="366" src="https://user-images.githubusercontent.com/93924525/177497939-4e69b221-c929-4011-89a7-92f832b2fb40.png">

Another assignee is to be given for this. Requirements and scope changes is better to be discussed with secret_girl#4386

**Comment by ivanturlakov** [comment]
Tested on staging

>Expected: Lock icons positioned underneath the balances, with a 5px vertical spacing between.

Also could be added digit dividers as shown in the design(block counter).

<img width="1182" alt="Снимок экрана 2022-07-21 в 18 02 18" src="https://user-images.githubusercontent.com/46903215/180247821-8d5c963c-52db-4cac-8809-346ae05c7872.png">
<img width="1175" alt="Снимок экрана 2022-07-21 в 18 02 52" src="https://user-images.githubusercontent.com/46903215/180247809-ab2d2045-f54c-4bdf-8a80-b6e0f3893fa9.png">
