### ISSUE TITLE
Pioneer: How fees Impacted by user choices

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2898]
Fees will be non-zero, covering both size of extrinsic parameters, and also computational costs.

Any input field which includes text that goes into the chain, such as the body or title of a blog post, ends up being stored on-chain, and this impacts the total transaction fee that must be paid. It would be useful to have a clear UX around communication how what the user is providing as inputs is impacting the final fee.

Atlas ticket about the same: 
- https://github.com/Joystream/atlas/issues/2834

## Scope

- [ ] Show component linked below here in the footer of every transaction modal and signer

Add transaction fees to all steps of all modals where user inputs are made

- #3240

eg in the bottom of this modal next to progress CTA

<img width="1253" alt="Screenshot 2022-06-09 at 18 45 43" src="https://user-images.githubusercontent.com/93924525/172839313-3b7ba2fa-1fa9-4be1-a900-fb378064817f.png">

⚠️ See how fees are displayed - we only need to include it on every step of every modal
<img width="708" alt="Screenshot 2022-06-09 at 18 53 25" src="https://user-images.githubusercontent.com/93924525/172840641-4f1e9321-0eb6-487d-8e95-da92d3c14dc4.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202170709011570) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
UX for fees handling: https://github.com/Joystream/pioneer/issues/1553

**Comment by MattAugustynowicz** [comment]
I don't think we need to show on screens with the creation of a proposal, for example, the stake amount visible at the bottom all the time, because we can see it in the left part of the modal, so here rather as simply a confirmation I will say yes - it is good that the fee is visible all the time. It should be right next to the CTA on the right side. 

The only change I would make additionally is the layout in which we show this data. At the moment, we have a large gap between the header and the amounts due to adjusting this field for large amounts. However, I don't see any obstacles for this header to be placed directly in front of the quantity. It looks much more natural, and with only one value (fee), it will not look like a coding error. 

[👉 Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8437%3A238535)
![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/8b72c97c-3cc7-4326-b531-678605e3684e)

At the last step, when signing the transaction or (if any) in modals where we have the required stake amount, and we do not see this stake amount on the left, as in the proposal view - we should show both amounts, one above the other as we have done so far. 

[👉 Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9848%3A383094)
![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/e3bd276b-38bf-4fc2-aa88-cffa6c28925d)
