### ISSUE TITLE
Same member listed twice as a worker

### ISSUE THREAD

**Issue by singulart** [Joystream/pioneer#2921]
## Scope
- [ ] Display only the current role for Workers

⛔ out of scope:
- [ ] #2937

<img width="1423" alt="Screenshot 2022-04-28 at 17 15 38" src="https://user-images.githubusercontent.com/93924525/165798539-274bbf9c-e3b6-4022-8144-f9e7074d547d.png">

_____

In my opinion, it makes little sense for the same user to be a worker of the same Working Group more than once. You are either a worker, or you are not :) The screen shot shows that some people are shown two times: 

<img width="417" alt="Screenshot 2022-04-26 at 15 41 59" src="https://user-images.githubusercontent.com/7863785/165302276-71eeb7bf-01fb-49e9-be34-4945495022a5.png">

Apparent reason is that they applied on one particular opening, then hired, then left, then applied again for the different opening, and hired again.

**Comment by traumschule** [comment]
> In my opinion, it makes little sense for the same user to be a worker of the same Working Group more than once.

It makes sense if you think of it as employments. You can be hired by the same firm twice or more sequentially and on different positions. This is why it helps to see each opening title in the tooltip (compare linkedin).

There's however another  bug because the lead is also listed as worker:
![lead-twice](https://user-images.githubusercontent.com/31551045/196041853-7c2ebb60-6b6a-4210-ba94-2c06eec8a369.png)
![builders](https://user-images.githubusercontent.com/31551045/196041846-2091f587-22ac-4f89-9f19-efa29ed0ecb8.png)
