### ISSUE TITLE
[USERSNAP] Bounties are failed, on another persons's end they are okay

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2957]
**Taken at**: https://dao.joystream.org/#/bounty/current
**Fields**:
- Houston, we have a problem.: Bounties are failed, on another persons&#39;s end they are okay
- Comment: I expect the bounties to show that they are not failed even though I haven&#39;t selected any membership.
- Feedback: jen4#8632

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e5a59f5d-8686-49b7-9abb-ad879d42ad26-annotated_a5aa5547-37e3-434f-85df-b087c219f4c5.png?etag=ba294c26f7f3a17814643ec539f893d6)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e5a59f5d-8686-49b7-9abb-ad879d42ad26-annotated_a5aa5547-37e3-434f-85df-b087c219f4c5.png?etag=ba294c26f7f3a17814643ec539f893d6)*

**Browser**: Chrome 100 (macOS Sierra)
**Screen size**: 1440x900
**Browser size**: 1800x918
**[Open #238 in Usersnap](https://app.usersnap.com/l/feedback/42832d71-1eea-49e6-bbc5-f325d3047e46?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Jen4, thanks for raising!


Can you clarify what does "On other members' end they look ok"?
And also elaborate on how is your bounties list different for a guest vs signed in member?

**Comment by jen4ph** [comment]
@dmtrjsg Before reporting this issue, I alerted the HR lead about this, and when he looked at this by himself the instead of "FAILED", on his end it was actually "WORKING PERIOD".
![WORKING](https://user-images.githubusercontent.com/96877192/166876179-d857d88f-c80a-4f08-94bf-6e76b7e40263.png)

As you have seen on the photo I attached with my report thru snapshot, I have signed in, just haven't selected the membership.
