### ISSUE TITLE
Forum UX Upd

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3029]
## Context
Forum during MVP dev phase was built around splitting the overall experience to tabulated pages and an overview landing page. The info architecture proved to be suboptimal and caused a number of change requests from the community members and JSG operations team.

Namely:

* #2429 
* #2426 
* #2951 
* #2952 
* #2437 
* #2428 
* #2438 
* #2734 
* #2785 

This ticket is aimed on surfacing all underlying use cases and optimising the forum UX experience for New users and Experienced users, including Forum WG Lead.

## Design
[Link to Figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8966%3A319910)

## Scope
No qa required:
* [x] #3183
* [x] #3184
* [x] #3651
* [x] #3165

To-test:
* [x] #3151 
* [x] #3152
* [x] #3153
* [x] #3154
* [x] #3157 
* [x] #3155
* [x] #3162
* [x] #3224 
* [x] #3352
* [x] #2440 
* [x] #3163

Out of scope ⛔ :
* [x] #3187

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203142073969108) by [Unito](https://www.unito.io)

**Comment by MattAugustynowicz** [comment]
Based on tests with several users, familiarization with the activities of other services having forums, our discussions, and knowledge, we come up with a proposal of forum solutions.   Let's start with what the user sees at the very beginning.

### The main page of the forum
[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9364%3A333164)

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/95480823/170501418-de2fbb03-ef2c-4f83-bbe3-33f36e388ee0.png">

People using the forum have indicated that recent posts are one of the most interesting information, so I propose that we put this at the top in the form of tiles on the carousel. Each will contain the time of publication, the author, the category in which it was added, the headline, part of the description, and a counter with replies.   Underneath, we will show categories as the central "hub" for moving around the forum - next to recent publications, it is the next most searched section. I suggest we drop the showing of the last thread and the popular thread inside the category tile. It wasn't the most visible and didn't work very well, and by splitting the categories into two columns, we wouldn't be using a massive amount of space as we currently do. Users were utterly unable to see the subcategory links, so it would be good to show them in a different, more visible form. I suggested that they could appear after hovering over a given category as pills, which would replace the current category description.

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/95480823/170501632-c4d70c67-274a-4140-8e61-b12ed8ec3526.png">

Additional information shown here is the number of topics in a given category. I proposed to use only the icon and the number next to it.  The last thing we have on the list is "my threads & watchlist." Of course, I remember the remarks that we want to put this information into "my profile," but before we jump in there, I suggest for "safety," we leave it at the end of the list in the same form so that we don't spend a lot of time developing it. This module is functionality that some users use, so they will intuitively look for it on the forum. When "my profile" is ready, we can simply hide the module and add a small note where the information is now.   The search has been moved directly under the header to keep it consistent with other pages on the platform.

The final change is to display "forum activities" as a cta at the top right of the screen. Forum activities function is an essential point for moderators, so they can quickly see recent posts and replies that have occurred. However, it is not very important for the rest of the users, so it would be good to show this as an additional side drawer.    

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/95480823/170501817-6365382f-2424-4bd5-bdb6-3aebbde67ee0.png">



### Category page
[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9364%3A339383)

We also move the search box right under the header. Additionally, I suggest that we show the most popular threads that have appeared within it on this page at the top. Below that, we could show the subcategories, which change similarly to the previous page into a two-column layout. Below that, we see our threads - unchanged.

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/95480823/170502115-cabc5f6f-2640-49ec-8a55-36f4dcd1ab4d.png">



### Thread page

   As for the direct entry subpage, improving its readability is described in detail here 👉 #2734 
   [👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9071%3A325093)
   
While introducing sticky headers is described here 👉 #2785 
   [👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9126%3A329404)



### Moderated post
   [👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9224%3A327717)

    The last change is showing comments which have been moderated. At the moment, the replies in the thread are simply hidden. In my opinion, we should show this post in some info-alert frame, with information that the post has been moderated, information about who moderated that, and the reasoning behind it. I would, of course, leave the option to see the original post. By default, the original post could be hidden. When expanded, you can see the entire reply, including the possibility to collapse.
   
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/95480823/170503122-520e0e1c-7178-4709-8bb0-34f9cd437054.png">

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/95480823/170503163-6a36f852-747c-4c19-a337-175c27a63332.png">

💸 Awesome people to whom we should give $30 for helping with the tests (discord handles):

• secret_girl
• adovrn

**Comment by traumschule** [comment]
> I propose that we put this at the top in the form of tiles on the carousel.
- The carousel slows navigation due to loading delay after every click. Load all ahead if you can.
- Do not truncate titles after 15 characters.
- Three columns are too busy and not useful in case of `YOUR WATCHLIST You don't have any watchlis` - just hide. 
- `FORUM ACTIVITIES` takes too much space for old info - limit to three days and hide rest, unless user clicks `see all`. Could be expandable right sidebar that collapses after some seconds / per default.

Just my ideas.

**Comment by traumschule** [comment]
> People using the forum have indicated that recent posts are one of the most interesting information

For reference this was finally implemented in #4881. Latest Threads came close but in practice not quite the same because changes in old threads stayed invisible.
