### ISSUE TITLE
Title stays sticky

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3187]
Make a sticky header on Forum Thread Page > [FIGMA LIN](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9126%3A329404)K

**Comment by stepien4soft** [comment]
For now we’re using generic components for the header. It’s the same for proposals, forums etc. Based on the designs we should add sticky functionality, white background etc. Should we implement it for all views or only for forum ( if we add it only for the forum general look will be inconsistently, but up to you)

**Comment by dmtrjsg** [comment]
@MattAugustynowicz can we look into this please and perhaps consider maintaining the off-white (light grey) header for consistency, or do you have smth else in mind to enable sticky header for Threads only?

**Comment by MattAugustynowicz** [comment]
@dmtrjsg I think all headings should be sticky. This would allow quick access to go back to the previous screen (if someone would not like to use the native browser option), or perform a contextual action such as creating a bounty, or adding a new proposal. I think we talked about this in one of the first meetings, that it should be sticky

**Comment by dmtrjsg** [comment]
Thank you for the analysis! @MattAugustynowicz can you pls paste it here for hte record?]

 This sounds a little more than we had the allowance for for general UX rn. While it sure does make sense, perhaps shall be parked for now as will not be insignificant.. :slightly_smiling_face: 
 
Sticky first level categories.. I am not sure tbf I have not ever seen this pattern :disappointed:

Let’s just park this one for now..?

**Comment by MattAugustynowicz** [comment]
@dmtrjsg Sure. Uploading a short version

"It looks very good when we have only one nesting, i.e. these first level tabs.

![image](https://user-images.githubusercontent.com/95480823/172170107-1cf6c729-e0aa-4ea8-b8ec-f4a520e29173.png)

The moment we have the second level navigation it actually takes up some space. We could of course taper their top and bottom padding a bit so they don’t take up 1/3 of the screen when scrolling, but it still doesn’t look the most attractive. At this point, the second level navigation would need to be redesigned to make this screen work and look as it should

![image](https://user-images.githubusercontent.com/95480823/172170205-4bd9abd3-c5e3-4984-a7e0-608378d50775.png)

We could make it so that only the first level navigation is sticky. Then we will achieve a victory in terms of visibility of contextual buttons, but as Dmitry also wrote, this will not be the best solution in terms of usability and user perception when part of the navigation disappears

![image](https://user-images.githubusercontent.com/95480823/172170595-5840efd9-a51a-425b-a1e2-3a3590d2e7fa.png)
