### ISSUE TITLE
New logic and UI for selecting staking account

### ISSUE THREAD

**Issue by RafalPloszka** [Joystream/pioneer#3238]
2. and 3. from https://github.com/Joystream/pioneer/issues/2300

AC:

- [ ] Account selection for staking purposes
- [ ] Handling situation when no accounts are available, but some might be suitable after funds are transferred

**Comment by ivanturlakov** [comment]
Tested on staging

**1. Account selection for staking purposes**

Stake recovered after unlocked for role-based locks; while other locks can be recovered automatically (like proposal locks, when they get rejected)

<img width="1173" alt="Снимок экрана 2022-07-05 в 14 23 53" src="https://user-images.githubusercontent.com/46903215/177319018-8f0ac41f-d57d-4128-9c9e-147cd4ca7c35.png">
<img width="1253" alt="Снимок экрана 2022-07-05 в 14 24 28" src="https://user-images.githubusercontent.com/46903215/177318999-c138a727-d6df-42df-bc26-d66a7398565a.png">

Proposal rejected

<img width="1175" alt="Снимок экрана 2022-07-05 в 14 27 53" src="https://user-images.githubusercontent.com/46903215/177319016-951b916c-1cdc-47ac-877a-9e28eeabae4b.png">
<img width="1252" alt="Снимок экрана 2022-07-05 в 14 28 38" src="https://user-images.githubusercontent.com/46903215/177319006-b0211b20-268d-421a-8f44-e92cf7df0ee3.png">

Bound to currently selected membership (ivant)

<img width="1247" alt="Снимок экрана 2022-07-05 в 14 49 58" src="https://user-images.githubusercontent.com/46903215/177321060-05b735e1-e6b1-49ac-8584-c02559d38935.png">
<img width="1247" alt="Снимок экрана 2022-07-05 в 14 50 19" src="https://user-images.githubusercontent.com/46903215/177321063-1d21ccb1-b6a3-4461-ae20-acb517d523f8.png">


Sufficient balance (> min staking amount) 

<img width="1253" alt="balance_" src="https://user-images.githubusercontent.com/46903215/177319008-05f64f85-da10-4fa8-b692-2ad9f27a2378.png">
<img width="1263" alt="balance" src="https://user-images.githubusercontent.com/46903215/177319013-8c006685-02b0-4c27-82df-faf7bd0e4c7a.png">


**2. Handling situation when no accounts are available, but some might be suitable after funds are transferred**

Proposal

<img width="916" alt="Снимок экрана 2022-07-05 в 14 58 44" src="https://user-images.githubusercontent.com/46903215/177322790-2fcf9786-d093-4ab7-a34b-770d2f267f93.png">


Applying to a role

<img width="1251" alt="Снимок экрана 2022-07-05 в 14 59 31" src="https://user-images.githubusercontent.com/46903215/177322844-dc35d9ae-a4ac-4a05-82b1-b991f18a413f.png">

**Comment by dmtrjsg** [comment]
@ivanturlakov thanks for thorough testing 💪 
@RafalPloszka over to you mate 🎾 

#### UI:

1. Selector needs to push the list down, and correctly overlays on top of the first account card.
3. Colour of disabled lock filling matches the border. Borders (horizontal delimiters) need to be visible. 
3. Space to be added between icons and balances

#### Tooltips upd for locks

> I ack this may be increase in scope but would be nice to customise for most common scenarios

Tooltip on proposal locks:
2. Change copy to “.. because it contains a proposal lock. Proposal locks are recovered, when they get executed. 
View lock details> (pointing to account page and lock details expanded)
Learn more about locks> (pointing to gitlab)”

Tooltip on role staking lock:
.. because it contains a role staking lock, which becomes recoverable after the role is terminated (subject to cooldown period for Leads). 
View lock details> (pointing to account page and lock details expanded)
Learn more about locks> (pointing to gitlab)”


#### When not enough tokens on account
. “This account does not have enough tokens tooltip”, looks like this is still to be implemented.


#### Single-membership validation

⚠️ 1️⃣ When all accounts are locked, display after accounts checks per selected-member:

2️⃣ Update copy in Suggestion box:
“All your accounts for current membership have locks preventing from using them for this proposal.

In order to proceed:

* Create new account using your wallet extension
* Move the required amount of tokens to your new account
* Start again and choose the newly created account 

:info_icon: It is strongly recommended to link all accounts to a single membership in order to correctly attribute  and benefit from the accumulated reputation on the network. 
"

**Comment by dmtrjsg** [comment]
Adding a follow up issue to include an anchor to the locks page and make them hyperlinkable: https://github.com/Joystream/pioneer/issues/3333

**Comment by dmtrjsg** [comment]
@RafalPloszka tooltip wording updated as agreed: 

"2. Change copy to “You cannot select this account because it has a lock preventing its usage for staking. Role stake can be recovered after the role is terminated, while proposal locks get recovered automatically, when proposals get executed.
Learn more about locks> (pointing to gitlab)”

**Comment by ivanturlakov** [comment]
Tested on staging

**UI**
1. Colour of disabled lock filling matches the border. Borders (horizontal delimiters) need to be visible. 
2. Space to be added between icons and balances.
<img width="1010" alt="Снимок экрана 2022-07-15 в 12 51 24" src="https://user-images.githubusercontent.com/46903215/179199702-8454e7a5-4d34-4d6a-8520-d0510730d9fb.png">
<img width="912" alt="Снимок экрана 2022-07-15 в 13 13 28" src="https://user-images.githubusercontent.com/46903215/179203392-44ccac56-0b0a-48e0-a7ce-01fb5ff034cb.png">


**Tooltips upd for locks**
<img width="1440" alt="Снимок экрана 2022-07-15 в 12 54 25" src="https://user-images.githubusercontent.com/46903215/179200347-1217279e-3930-424f-a028-dbd000232aeb.png">
<img width="1440" alt="Снимок экрана 2022-07-15 в 13 06 52" src="https://user-images.githubusercontent.com/46903215/179202544-d543bb14-16f9-4ec2-a9c1-26eef3a21e05.png">



**Single-membership validation**
<img width="916" alt="Снимок экрана 2022-07-15 в 13 02 50" src="https://user-images.githubusercontent.com/46903215/179201698-726366dc-fff7-4f4f-bedd-bf5517c127af.png">

**Comment by dmtrjsg** [comment]
@ivanturlakov looks like all good, thanks a mil for testing it and bringing over the finish line, assigning ready-for-prod label. Pls ping me if you disagree :)
