### ISSUE TITLE
[USERSNAP] Tried to resubmit candidacy, transaction failed

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3290]
**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: Tried to resubmit candidacy, transaction failed
- Comment: A previous submissed was interrupted due to another pioneer issue. I just resubmitted it without deleting the other candidacy.

Would be great if pioneer could pick up where it got interrupted last - just place the candidacy with the second transaction and skipping the first if member already submitted a candidacy.

```
Transaction error: ExtrinsicFailed
on network: wss://rpc.joystream.org:9944
in block: 0xbb49fd3958ad0974ab47d520cf4abf27752c0ceac0bcf7cd986bd6e5418aabde
```
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3f0f95b2-3e58-4a2e-81b3-d88553d18ab9-annotated_651d75cb-4a6e-44b2-97c3-320e58ae03d8.png?etag=11e716db2d18969d206ce00acac8fa17)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3f0f95b2-3e58-4a2e-81b3-d88553d18ab9-annotated_651d75cb-4a6e-44b2-97c3-320e58ae03d8.png?etag=11e716db2d18969d206ce00acac8fa17)*

**Browser**: Chrome 102 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2160x1429
**[Open #286 in Usersnap](https://app.usersnap.com/l/feedback/0282a947-158b-4d7c-8ea5-22874d5336e1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
related to https://github.com/Joystream/pioneer/issues/3291

**Comment by dmtrjsg** [comment]
@ondratra do you know if it would be possible to resubmit the candidacy or edit the candidacy note?

**Comment by ondratra** [comment]
Candidacy note can be changed anytime via `set_candidacy_note`. Candidacy can also be withdrawn during the announcement period via `withdraw_candidacy`. After the candidacy is withdrawn, it can be reannounced once again.

I'm a little bit confused about how the transaction was "interrupted". Since blockchain transaction is atomic, the candidacy was either fully submitted or not. Theoretically, it is possible that the transaction got hanging in Pioneer or the blockchain wallet without actually being relayed to the blockchain, or something similar could have happened. In such cases, a combination of a refreshing webpage, deleting cookies, deactivating and reactivating a browser's wallet plugin, or something of a sort could help.

**Comment by dmtrjsg** [comment]
@ondratra thank you for your detailed answer ⭐ We will triage this with the Pioneer folks now, but looks like we've got what we asked for 🙇‍♂️

**Comment by traumschule** [comment]
> I'm a little bit confused about how the transaction was "interrupted".

When announcing a candidacy pioneer makes two transactions to first submit then edit it. The user has to sign each individually and sometimes the second is skipped (due to a pioneer issue or user not signing it).

=> Pioneer should be able to recognize the former blank candidacy and offer to edit it (ideally from local storage without having to reenter everything).

**Comment by dmtrjsg** [comment]
> set_candidacy_note

since that is possible, we need to design the flow to change it. Moving to design pipeline. This is a low prio since rarely would happen

**Comment by dmtrjsg** [comment]
⚠️ Partly QN > to change the protobuff

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/election
wss://54.227.116.57.nip.io/ws-rpc

To test I am announcing a candidacy but skipped the last step(Set candidacy note) by switching to a Profile page. Then come back to the Election page.

<img width="1188" alt="Снимок экрана 2022-11-01 в 11 57 24" src="https://user-images.githubusercontent.com/46903215/199212891-13200bff-337b-4d8c-ba0d-0dfe75e05ec5.png">
<img width="1183" alt="Снимок экрана 2022-11-01 в 11 57 55" src="https://user-images.githubusercontent.com/46903215/199212885-314b3e8d-a4ac-4622-8015-dae31c32c3a9.png">

### When trying to reapply

<img width="691" alt="Снимок экрана 2022-11-01 в 11 59 35" src="https://user-images.githubusercontent.com/46903215/199213121-f8617848-a15d-485b-8c50-e0ba1f4c06f7.png">

### Added other candidates > Voting  > Revealing

<img width="1185" alt="Снимок экрана 2022-11-01 в 12 12 26" src="https://user-images.githubusercontent.com/46903215/199213392-9141d01f-7d30-428a-ab9c-61f6fbc4b419.png">


### Election results

<img width="913" alt="Снимок экрана 2022-11-01 в 12 30 19" src="https://user-images.githubusercontent.com/46903215/199213950-66953ed1-aad2-4ca1-a083-c13392f64fd9.png">


<img width="1184" alt="Снимок экрана 2022-11-01 в 12 16 51" src="https://user-images.githubusercontent.com/46903215/199213797-2e44f596-c9d3-44d6-8478-14fa9e2d18eb.png">
