### ISSUE TITLE
Test Genesis Vesting

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3452]
## Context

Same as #3404 but set up in the Genesis block

This issue must be tested in scope of 2nd round of QA, Env details are in the Epic pls see pioneer/3577>
https://github.com/Joystream/pioneer/issues/3577

⚠️ Importantly, the vesting lock in this testing will be pre-allocated in the Genesis block for the four test accounts: Alice, Bob, Charlie, Dave. The pace of unlocking per block and total allocation will vary to try and equip the team with right amounts for positive and negative scenarios testing.

'Alice': Total Balance 50k, Liquid balance 0Joy, Period to Unlock 10 days (43200 blocks) gradual unlock
'Bob': Total balance 10k, Liquid balance 0 Joy, Period to Unlock 5 days (72000 blocks) fast unlock
'Charlie': Total balance 3k, Liquid balance 0 Joy, Period to unlock 10 days (43200) slow unlock
'Dave': Total Balance 1k, Liquid balance 0 Joy, Period to unlock 100 days. (1440000 blocks) Negative scenarios focus, where funds are insufficient for stuff

Use subkey to fetch the keys for the above accs:
>☝️ Case sensitive, and double slash

<img width="437" alt="Screenshot 2022-08-29 at 15 35 01" src="https://user-images.githubusercontent.com/93924525/187226643-b9ac0c09-1cbc-487d-85d6-98d24165966c.png">

## Scope

* [ ] Setup any of the above accounts as a staking account for a member, and try to use it for applying to a role. Stake with 0.09 full amount (ex fees)
  * You may need to claim some unlocked tokens, through `vesting.vest()`, for transaction fees. 
* [ ] Assuming success:
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
* [ ] After a few more blocks, do another `vesting.vest()`:
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
* Slash the Worker for half the stake.
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
* Quit and unstake the Worker. Once done:
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)  
- [ ] Verify that that you can’t transfer funds that are locked in vesting
- [ ] Verify cannot claim more funds than unlocked in vesting

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202705523548356) by [Unito](https://www.unito.io)

**Comment by oleksanderkorn** [comment]
## Current balance of Alice:
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/9252017/187930103-6b72dd6a-4e8a-4c50-a048-c85fc8c2b3f0.png">

## Membership cannot be created using vested balance (Expected Behaviour) :
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/9252017/187929792-77be9bf4-36ab-4001-94c5-981582b5d352.png">

## Claimed the vested amount:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/9252017/187931893-40bba8a8-8dd9-47e5-83ce-f65edc75a5ec.png">

## Logs:
```
Successful transaction: Withdraw, VestingUpdated, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0x13cdbc7185d0c341d43063405241dda98a4412edea26c3572055ae29f035f132
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x13cdbc7185d0c341d43063405241dda98a4412edea26c3572055ae29f035f132
```

## Current Balance:
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/9252017/187932235-f4dc229e-5ee0-4d93-bf07-c65d048f52b5.png">

## Transferring max amount to another account: 

### Max available amount input is not possible (i assume because of the fees ):

<img width="878" alt="image" src="https://user-images.githubusercontent.com/9252017/187932476-8745fc0f-3735-4048-9fa5-8d142ad2a459.png">

### If I deduct 0.01 joy of max amount validation passes:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/9252017/187932879-da650761-1ad5-4906-8d95-1353f4db260d.png">

### On the Next screen button sign is Inactive

<img width="881" alt="image" src="https://user-images.githubusercontent.com/9252017/187933121-b4fa3661-b6d1-46b2-b39a-6a239dce63a8.png">

### Transfer without decimal points value passes:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/9252017/187933527-5239baad-d636-4cf6-b0c5-840c6c7ad264.png">

<img width="881" alt="image" src="https://user-images.githubusercontent.com/9252017/187933590-882d8e70-7a4d-4884-a898-0bc8bfc4e6dc.png">

### Logs 

```
Successful transaction: Withdraw, Transfer, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0x17bf0c905a8465d5ad344f311273d787c0805bc1f82f0800377b957cf96babcf
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x17bf0c905a8465d5ad344f311273d787c0805bc1f82f0800377b957cf96babcf
```

## Balance After transferring max available amount:

<img width="1653" alt="image" src="https://user-images.githubusercontent.com/9252017/187933811-1d20d466-7710-4af0-a3a1-f1fdc2005043.png">


## Another claim after waiting a few blocks

<img width="720" alt="image" src="https://user-images.githubusercontent.com/9252017/187934299-ec2027e0-d2e4-4215-88db-8a7bc2957e8c.png">

### Logs 

```
Successful transaction: Withdraw, VestingUpdated, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0x73702a7aa2e9e90a83a15f3d7ce69fd4786edb4fdcec67090ce804d30b41bf75
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x73702a7aa2e9e90a83a15f3d7ce69fd4786edb4fdcec67090ce804d30b41bf75
```

### Balance 

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/9252017/187934497-4172e4d3-08a6-423b-89bf-b9ce5afd8b9f.png">

## Verify cannot claim more - there is no possibility to claim a specific amount, there is no amount in the `vesting.vest` call.

**Comment by oleksanderkorn** [comment]
## Apply to the role using vested balance:

### Balance 

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/9252017/187948884-3264792f-f29f-454c-a66c-330783348a73.png">

###  Application
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/9252017/187948639-31648122-efdd-420f-ba16-bdca1d8ba731.png">
<img width="914" alt="image" src="https://user-images.githubusercontent.com/9252017/187949212-9b857d45-7a63-40c9-9048-55e2522ec168.png">

### Logs 

```
Successful transaction: Withdraw, StakingAccountAdded, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0xeee498e493ebe4201a972be817d686e2f44679b7905fe321e1019eb4d648a997
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xeee498e493ebe4201a972be817d686e2f44679b7905fe321e1019eb4d648a997
info.ts:1 Successful transaction: Withdraw, StakingAccountConfirmed, ItemCompleted, AppliedOnOpening, ItemCompleted, BatchCompleted, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0x9ebbfe675a01d074dc1c8c301a98192fc7d0950d526c53f6b090a09cb3249a7b
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x9ebbfe675a01d074dc1c8c301a98192fc7d0950d526c53f6b090a09cb3249a7b
```

### Application successful:

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/9252017/187949527-565bdb6e-0bf4-4741-a8c9-f4be76b91b50.png">

**Comment by oleksanderkorn** [comment]
## Proposal to hire Alice as DWG Lead failed:
https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/8

## Retried proposal:
https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/9

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/9252017/187951779-34d4983a-607e-427d-acf6-82c6090e8d12.png">

### Logs Execution failed again:  

```
Successful transaction: Withdraw, Voted, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0xbc620d0a75f1ffef6658e0126cd6bd8572415ab2898510c2e6a4f4866b9cfd04
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xbc620d0a75f1ffef6658e0126cd6bd8572415ab2898510c2e6a4f4866b9cfd04
```

**Comment by oleksanderkorn** [comment]
## Slash lead worker with 1/2 of the stake

Link: https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/12

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/9252017/187954890-47d9685d-0b73-4d18-ade9-47903d8fef49.png">

Logs (Proposal Executed): 

```
Successful transaction: Withdraw, Voted, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0xa14655c7376e7322e9763e248f3b6b567d131d770aacf73f1983f1bf23f6a7e5
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xa14655c7376e7322e9763e248f3b6b567d131d770aacf73f1983f1bf23f6a7e5
```

### Balance:

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/9252017/187955356-c681986d-e98f-405b-858d-8fb3559cfd4f.png">

**Comment by oleksanderkorn** [comment]
## Quit and unstake the Lead Worker

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/9252017/187955567-cbf54110-b4ab-4344-a8d2-52d475a52b21.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/9252017/187955807-f070e17a-53c1-4709-b841-c5f62cd9cc14.png">

<img width="930" alt="image" src="https://user-images.githubusercontent.com/9252017/187955876-d6a2898f-642a-4778-99a5-5f10f9cc7c25.png">

### Logs

```
Successful transaction: Withdraw, WorkerStartedLeaving, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0x0e77bc761c72723db53bf3c70ec19783b19df9a5474df3ee1a21f39dece484bb
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x0e77bc761c72723db53bf3c70ec19783b19df9a5474df3ee1a21f39dece484bb
```

### Balance after leaving the role

<img width="1653" alt="image" src="https://user-images.githubusercontent.com/9252017/187956267-46f63f53-d5aa-43fd-82f6-b4418bd4c076.png">
