### ISSUE TITLE
[USERSNAP] Incorrect wording about Membership Lead

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3492]
## Scope

- [x] Update the last sentence of the copy on top of the modal to  "..to find out about the upcoming "Update Working Group Budget" and "Set Membership Lead Invitation Quota" proposals."
- [x] Update the Link to point to "https://discord.gg/DE9UN3YpRP"; Update the copy before the link to "Go to Discord ➡️"

## Context
______

**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/profile/memberships
**Fields**:
- Houston, we have a problem.: Incorrect wording about Membership Lead
- Comment: The Membership Lead isn&#39;t human-operated role. Rather, it&#39;s a system role. So asking users to &#34;talk to&#34; the Lead of Membership WG is quite misleading: &#34;Speak with the Membership Working Group Lead on Discord to find out about the upcoming funding proposals for this group.&#34;

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a4255d22-0a2d-4b7c-ac5d-4f67ef00c3d9-annotated_45d93300-bd6a-4c2e-b777-cd804c0a4be4.png?etag=8d28b048990aedc0ed78fdd6d4ea316a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a4255d22-0a2d-4b7c-ac5d-4f67ef00c3d9-annotated_45d93300-bd6a-4c2e-b777-cd804c0a4be4.png?etag=8d28b048990aedc0ed78fdd6d4ea316a)*

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1512x982
**Browser size**: 1512x791
**[Open #329 in Usersnap](https://app.usersnap.com/l/feedback/ad1a80e1-d51d-4beb-9882-7f45348be3f2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
I'm a little curious as to how you get to this screen, given that this person presumably (a) has tokens, but (b) is not a member. If I'm reading that correctly, they shouldn't be able to invite anyone due to b, so not sure why this is shown.
Anyway, if there aren't enough funds/invitations in the budget/"bank", it's nice to show something up front.

Regarding the comment/question:
The Lead is a role like anything else, and they (can) operate a faucet with their key. The "Set Membership Lead Invitation Quota" provides the memberships, whereas the budget provides the funds (for all membership invitations, not just those that goes through the faucet).

As JSG has had the role, and operated the faucet on the testnet, and likely will for some amount of time, means we have delegated the task of paying attention to these numbers. Whether it should be the council or the Lead actually doing that In the future is another story.

I would say that the phrasing of the final part of the last paragraph is slightly off - a "funding proposal" will be read as the "Funding Request" proposal, not the relevant "Set Membership Lead Invitation Quota" and "Update Working Group Budget" (for the membership group).

**Comment by singulart** [comment]
> I'm a little curious as to how you get to this screen, given that this person presumably (a) has tokens, but (b) is not a member. If I'm reading that correctly, they shouldn't be able to invite anyone due to b, so not sure why this is shown. Anyway, if there aren't enough funds/invitations in the budget/"bank", it's nice to show something up front.
> 
> Regarding the comment/question: The Lead is a role like anything else, and they (can) operate a faucet with their key. The "Set Membership Lead Invitation Quota" provides the memberships, whereas the budget provides the funds (for all membership invitations, not just those that goes through the faucet).
> 
> As JSG has had the role, and operated the faucet on the testnet, and likely will for some amount of time, means we have delegated the task of paying attention to these numbers. Whether it should be the council or the Lead actually doing that In the future is another story.
> 
> I would say that the phrasing of the final part of the last paragraph is slightly off - a "funding proposal" will be read as the "Funding Request" proposal, not the relevant "Set Membership Lead Invitation Quota" and "Update Working Group Budget" (for the membership group).

I clicked on "Invite a Member" CTA button in the overview screen.

**Comment by dmtrjsg** [comment]
⚠️ Link requires an update. Currently points to old gitbook, but shall point to discrod.  Awaiting guidance from @singulart wrt to best URL to update the link on the modal.
