### ISSUE TITLE
Rename Total Balance to Free Balance

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3501]
## Context
https://joystreamworkspace.slack.com/archives/C039QJHMM38/p1660553551656179

Correct behaviour:
![Screenshot 2022-08-15 at 12.00.34.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/298d18b5-9b76-44c9-855a-5675c87eed7a)

## Scope
* Update Total Balance Widget and Account Components to "Free Balance"
![Screenshot 2022-08-15 at 11.52.32.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/b5a3767e-4146-4e41-94e8-40a8434a60e8)
* Update Tooltips wording on Total Free Balance to "
"`Total balance from all connected accounts. Free balance is  a sum of Usable Balance and Locked Balance. Free balance is used to cover transaction fees. In cases when Free balance is comprised from Locked Funds exclusively, the Free Balance will decrease, while the Locked Balance will remain intact.` "

* Rename Transferable Balance to Usable Balance
![Screenshot 2022-08-15 at 11.52.45.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/9d249c03-d0cc-492f-a248-1abd4e4b00fd)
* Update Tooltip on Usable Balance to 
"`Usable Balance is balance free from any locks. It can be transferred to any account, used for staking and covering transaction fees.`"

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202798654377867) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
I don't get the problem we are trying to solve here, is it to replicate balance concepts from the chain?

If so, we don't need to have balance concepts that mirror low level Substrate specific balance concepts (which are quite bad). We have balance categories that reflect functional categories related to user objectives, this is much better in my mind. I don't believe we have had a single user who actually understands the Substrate version of `free balance`, because even I cannot precisely define it off the top of my head effortlessly, that entire conceptual apparatus is a mess.

**Comment by dmtrjsg** [comment]
Thanks for the feedback! Closing as such
