### ISSUE TITLE
Update Gateways WG to be called Apps

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3583]
## Context
- https://github.com/Joystream/joystream/issues/4230

## Scope

- [x] Update WG name from "Gateways" to "Apps"
- [x] Update description to "Apps group runs multiple video streaming apps working on Joystream blockchain and provides support to all exteernal app operators."
- [ ] Update Icon
- [x] Add Tooltip. "Learn more about this group [[external source icon]](https://joystream.gitbook.io/testnet-workspace/system/gateways)." 

 description and icons, same with proposal selection of WG.

**Comment by toiletgranny** [comment]
@dmtrjsg a few quick clarifying questions:
1. What is/are the Pioneer page(s)/view(s) this affects?
2. Where should the name and description be updated?
3. What is the current icon for Gateways WG? In Figma, there are multiple icons with "Gateway" in their names; I don't know which we're talking about.
4. By "[external source icon]", did you mean any specific icon that's already used in Pioneer? Where should this tooltip be added?

**Comment by dmtrjsg** [comment]
Hey Adam, 

Sure so 

Here's the url to the page https://dao-git-carthage-joystream.vercel.app/#/working-groups

Screenshot of the current state:
<img width="1489" alt="Screenshot 2022-10-18 at 11 19 33" src="https://user-images.githubusercontent.com/93924525/196363025-0d8247f5-b71c-4fbb-9050-bce4b2ea547b.png">

Link to tooltips issue for working groups:
https://github.com/Joystream/pioneer/issues/2680

**Comment by toiletgranny** [comment]
Ok, @dmtrjsg, this is ready to be reviewed. Design in Figma [can be found here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11275%3A434605). A few notes:

1. I put the "Learn more" link at the end of the description, as putting interactive elements in tooltips is typically considered a bad UX practice. Hope this recommendation is okay.
2. It appears there's a character limit on each WG description, which is implied and inherited by the layout and the way each Working group row has been designed and implemented. For this reason, I had to cut down the description you provided by just a touch so that it's contained within max ~105 characters. I hope the sorter version is still technically correct: "Apps group runs multiple video streaming apps on Joystream blockchain and supports all external operators."

![image](https://user-images.githubusercontent.com/35307309/196412982-3c8f5021-e3bf-4175-9427-338fea47010b.png)

**Comment by dmtrjsg** [comment]
@toiletgranny  thanks for it, good stuff

Re description and icon, sure thing! 

Q: The pattern of pointing to external handbook from the tooltip is already adopted in quite a few places. Also issue #2680 suggests to put the tooltip next to the title and saves from calibrating the copy for all other groups to ensure that learn more is visible.. Or would yo suggest to wrap the text if its longer and always show "learn more" in the WG description?

**Comment by toiletgranny** [comment]
@dmtrjsg Sorry, I wasn't aware that this would apply to all groups. Having given it more thought, I think going with the tooltip seems to have more sense now, considering it's an already established pattern and the time and effort required to do otherwise.

I updated the designs, added icons, and tooltips, and brought back your original copy for the description. :)

![image](https://user-images.githubusercontent.com/35307309/196652408-8e9f2327-705d-4858-ab8f-31898ad76a88.png)

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/working-groups

### ✅ Items listed in scope updated
<img width="1436" alt="Снимок экрана 2022-10-29 в 15 11 56" src="https://user-images.githubusercontent.com/46903215/198830760-7edbd0f2-73b8-4ffc-888f-30d42914f289.png">

@dmtrjsg there are some places where the old name remains

<img width="1439" alt="Снимок экрана 2022-10-29 в 15 12 13" src="https://user-images.githubusercontent.com/46903215/198830762-c8559ea3-db5f-472f-a6c1-356ee1a810e6.png">
<img width="538" alt="Снимок экрана 2022-10-29 в 15 17 37" src="https://user-images.githubusercontent.com/46903215/198831165-59a824aa-3581-49f3-ae7d-95276cd17987.png">

**Comment by traumschule** [comment]
did not check current content, just a grep on dev minus changed files:

- packages/ui/src/working-groups/types/locks.ts:  gatewayWorkingGroup: 'Gateway Worker',

- packages/ui/src/working-groups/constants/index.ts: gatewayWorkingGroup: 'Gateway',

- packages/ui/src/working-groups/components/WorkingGroupImage.stories.tsx:        Group names: bandwidth, storage, forum, membership, content, discovery, operations, gateway, council or{' '}

- packages/ui/src/accounts/types/balances.ts:  'Gateway Worker',

- packages/ui/src/accounts/model/lockTypes.ts:  ['wg-gatew']: 'Gateway Worker',

- packages/ui/src/accounts/components/AccountLocks.tsx:  'Gateway Worker': <GatewayWorkerIcon />,

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/working-groups
wss://54.163.55.37.nip.io/ws-rpc

The old name still remains in some places

<img width="601" alt="Снимок экрана 2022-11-18 в 15 16 03" src="https://user-images.githubusercontent.com/46903215/202713798-e2e3a0d2-76ea-4e1c-ba27-e5fea79ae1d5.png">
<img width="819" alt="Снимок экрана 2022-11-18 в 15 13 20" src="https://user-images.githubusercontent.com/46903215/202713805-9c2bfc31-b23d-4cc1-975d-8373bcd91d52.png">

**Comment by dmtrjsg** [comment]
@WRadoslaw pls feel free to take care of the last few small bits

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/working-groups
wss://34.230.5.182.nip.io/ws-rpc

Name updated 👍
