### ISSUE TITLE
[USERSNAP] can't recover balances from my profile

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3591]
**Taken at**: https://dao.joystream.org/#/profile
**Fields**:
- Houston, we have a problem.: can&#39;t recover balances from my profile
- Comment: recover balance
- Link to polkadot block: ?

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/dd734c09-1180-4aea-8258-31e211cb37bd-annotated_521eed09-f122-4ee5-a07e-9754ad969869.png?etag=8a771616e45bcbba1abf3fa44c33008f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/dd734c09-1180-4aea-8258-31e211cb37bd-annotated_521eed09-f122-4ee5-a07e-9754ad969869.png?etag=8a771616e45bcbba1abf3fa44c33008f)*

**Browser**: Chrome 104 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x722
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/b37e681c-2d1f-49c7-92a0-89468b521dce_screen_recording_309826c3-c315-49a0-a4ce-56f25a9ea6f3.webm?etag=6d587cfcc9c85e2239d62d99fede9968)**
**[Open #333 in Usersnap](https://app.usersnap.com/l/feedback/5f58d1e6-1868-4ef5-ac30-92e436ec5830?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
@dmtrjsg OK, as I see it, the problem is that we display CTA to recover lock which in the case of worker locks is not correct. Stake for application/worker will be recovered at the time of:
- for application at the time of withdrawal
- for worker, after leaving the role and passing the `leaving unstaking period`.

The fix will be:
- less time to implement - remove button and inform the user about how to claim lock with some text (maybe redirection to wg page)
- more time - fetching workerId and displaying LeaveRole modal, but the problem is that for application since we don't have withdraw application flow in the application

**Comment by dmtrjsg** [comment]
Thank you sir for looking into it 🎩.. let's go with Remove button and inform the user via Tooltip. 

Copy 

"Stake for WG role application and active role participation as worker or lead will be recovered at the time of:
for application - at the time of withdrawal.
for active role -  after leaving the role and elapsed leaving un-staking period."

**Comment by dmtrjsg** [comment]
After brief chat with Radek, decided to override the tooltip with the "recoverable after.." ETA, similar to this design:
<img width="344" alt="Screenshot 2022-09-21 at 09 21 50" src="https://user-images.githubusercontent.com/93924525/191429300-22eec14d-eb7f-4714-a8ee-4b001f8f5783.png">
