### ISSUE TITLE
Pioneer "Under Maintenance" Screen

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3636]
## Scope

- Implement the placeholder image for maintenance "mode" to be put on during carthage network staggered rollout.
- Link to [Figma>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=11193%3A434407) (one on the right)
- ⚠️ Copy upd: 
"Pioneer is currently undergoing maintenance work to ensure sync up with the updated version of runtime and new features release goes smoothly. 
We should be back shortly. In the meantime, feel free to connect with us on Discord."
- Link for discord> https://discord.gg/DE9UN3YpRP 

## Design Preview

<img width="427" alt="Screenshot 2022-10-04 at 12 53 19" src="https://user-images.githubusercontent.com/93924525/193777476-5065ea46-5719-4eb2-9131-109e3b56a923.png">

## QA

Can be tested at https://pioneer-2-git-carthage-joystream.vercel.app/

**Comment by toiletgranny** [comment]
@dmtrjsg I cooked up two options for you to choose from, with my recommendation being the first one, with the illustration on the top. Let me know if there's something else you'd like to explore. 

https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=11193%3A433937

Since you mentioned the rollout might take a few days, I thought we could also include a link to Discord, not to leave users hanging.

**Comment by dmtrjsg** [comment]
@thesan pls advise on how to test it..

**Comment by dmtrjsg** [comment]
ℹ️  can be tested on
