### ISSUE TITLE
Forum: Watchlist tab

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/pioneer#3642]
Prepare watchlist screen based on the My Thread tab implementation

(Part of https://github.com/Joystream/pioneer/issues/3029)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203073054886860) by [Unito](https://www.unito.io)

**Comment by ivanturlakov** [comment]
Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/#/forum/watchlist
wss://34.230.5.182.nip.io/ws-rpc

Didn't see changes since the last [test](https://github.com/Joystream/pioneer/issues/3162#issuecomment-1333466395)
@dmtrjsg Am I using the correct testing env?

https://user-images.githubusercontent.com/46903215/206699789-c0360ec9-dcd2-4c37-a10b-933f8048d86d.mov

**Comment by dmtrjsg** [comment]
@traumschule  the watchlist needs to be implemented as slider that we already have here> 

https://dao.joystream.org/#/forum

pls feel free to assign

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-2grqxk4u7-joystream.vercel.app/#/forum/watchlist
wss://34.230.5.182.nip.io/ws-rpc

Works as expected on this env


https://user-images.githubusercontent.com/46903215/212340459-1005a99b-8c80-4b4f-9443-725b194209b7.mov
