### ISSUE TITLE
Add tooltips to Candidacy Staking Acc and Vote Staking

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3682]
#### For Candidacy staking

The account holding the stake for the candidate. After announcing the staking account will have locked up REQUIRED_CANDIDACY_STAKE under the relevant council lock. If the candidacy fails - either because the election cycle fails or the candidate receives too few votes, then this lock can be removed by the candidate, otherwise it remains on into the councilorship. Be aware that this stake contributed towards the candidacy does not contribute towards the final election outcome, hence exceeding the minimum bound would only be done for signaling or other social purposes.

Learn more> "https://joystream.gitbook.io/testnet-workspace/system/council#candidacy"

####  For voting stake 

:one: On both! Reveal Vote screen and Past Elections  for "My stake":![Screenshot 2022-10-11 at 14.24.17.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/23dbfa91-cf41-45cc-9432-c191c7f62766)

:two: Rename to "My contributed votes"

:three: Add tooltip after label: “Vote for your own membership with the same account as used for council candidacy creation counts towards the progress. Please note, this will in a voting lock applied to this account, which may only be withdrawn in the end of the council period if you win the election and released immediately if your candidacy gets outvoted by others. Voting locks are non-rivalrous.
Learn more > External link icon "https://joystream.gitbook.io/testnet-workspace/system/council#vote"

**Comment by traumschule** [comment]
@mkbeefcake can you have a look please

**Comment by mkbeefcake** [comment]
Ok. i will check it

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/election
wss://34.230.5.182.nip.io/ws-rpc

### ⚠️ For Candidacy staking - Tooltip didn’t changed 

The account holding the stake for the candidate. After announcing the staking account will have locked up REQUIRED_CANDIDACY_STAKE under the relevant council lock. If the candidacy fails - either because the election cycle fails or the candidate receives too few votes, then this lock can be removed by the candidate, otherwise it remains on into the councilorship. Be aware that this stake contributed towards the candidacy does not contribute towards the final election outcome, hence exceeding the minimum bound would only be done for signaling or other social purposes.

Learn more> "https://joystream.gitbook.io/testnet-workspace/system/council#candidacy"

<img width="654" alt="Снимок экрана 2023-01-11 в 14 00 45" src="https://user-images.githubusercontent.com/46903215/211801737-dd40ae59-41ea-441a-82c2-49d8b5e5b71e.png">

### ⚠️ For voting stake - Wrong "Read more" link (council#candidacy, should be council#vote)

<img width="1440" alt="Снимок экрана 2023-01-11 в 13 44 07" src="https://user-images.githubusercontent.com/46903215/211802457-042727d6-f114-4f1c-965e-ece17a55c1a3.png">
<img width="1203" alt="Снимок экрана 2023-01-11 в 13 49 58" src="https://user-images.githubusercontent.com/46903215/211802462-7925e54a-e660-4c78-8dab-b61e94634bb1.png">

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-staging-joystream.vercel.app/#/election/past-elections/000001p8
wss://34.230.5.182.nip.io/ws-rpc

### ✅ Candidacy staking
<img width="1440" alt="Снимок экрана 2023-01-12 в 14 19 03" src="https://user-images.githubusercontent.com/46903215/212070825-04acf0c9-0bbf-407b-8879-6d609251791e.png">

### ✅ Reveal Vote screen
<img width="1440" alt="Снимок экрана 2023-01-12 в 14 39 35" src="https://user-images.githubusercontent.com/46903215/212070839-22423aad-ed15-42f3-be54-9cf6d54bc3af.png">

### ✅ Past Elections
<img width="1440" alt="Снимок экрана 2023-01-12 в 14 49 57" src="https://user-images.githubusercontent.com/46903215/212070851-b12ac99f-2828-4357-8211-74cdde108e9d.png">
