### ISSUE TITLE
Proposal search: Proposer selection is not being updated

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3714]
Testing #3710 i noticed that proposers are always the same and do not match displayed proposals.

Task: populate the form with actual proposal authors (of all proposals or for selected type, status, timeframe).

![proposers](https://user-images.githubusercontent.com/31551045/196571917-79e94754-fa45-4300-bba5-7a5fa5c77e2e.png)

**Comment by dmtrjsg** [comment]
@traumschule we suggest to switch the select (drop down) with the input..

Placeholder copy will need to be "Type proposer name" ... and once user starts typing we display the matching results in the list to pick from. Once you select a result, it populates the field and runs search on it. 

If you click on it again, then cursor just moves to the field invite user to change the string.. 

Rationale: Since the select is a single option / not multi value combo box, this should work. Let me know what you think?

**Comment by dmtrjsg** [comment]
I'm pretty flexible tbf.. @WRadoslaw what you recon mate? pls share your thoughts here..

**Comment by WRadoslaw** [comment]
> sounds good. What's your thought on
> 
> * Limit proposers query to selected type / status (if non-empty)
> * Have (all / latest X / of past month) proposals on state to instantly filter locally

1. The problem is that the suggestion rn and in general is based on normal member query, which do not have relation with proposals in any way, so there really isn't a simple way I can think of that offers such feature. 
2. Seems like quite over-fetching, I don't really see how it would improve the process, could you elaborate of what you want to achieve?

@traumschule

**Comment by traumschule** [comment]
How to get suggestible proposers?
The case is user wants to search for proposals within the last month but no more than X and vaguely remembers the author, maybe the type too.
My approach is to effect that query entering `Past Proposals` and save the result on state / localstorage.
This unlocks limiting proposers to actual authors vs all members and filtering suggestions further on input.
A non-empty `type` filter would additionally reduce suggested proposers to authors of proposals of the selected type.
Does this make sense?

Caching was also discussed today in context of https://github.com/Joystream/pioneer/pull/3635#issuecomment-1285618128
https://discord.com/channels/811216481340751934/812344874099277824/1032667657314521191
It seems there are multiple places that could benefit from such a proposal cache.

**Comment by dmtrjsg** [comment]
@traumschule 

Thanks for the suggestion, after having discussed the effort involved in making this happen I am afraid we will need to direct our efforts on more strategic items. There is no relation between Members and Proposal types, so it will be really hard and expensive to introduce I am afraid.

Nevertheless to pursue the attempt to improve the problem and enhance the usability, we suggest  to change the component to autocomplete instead of select. 

So for the time being (in absence of the proper Backend and to avoid local storage tricks) to go forward with the exact same component, but remove the static list of the first 4 members from the drop down. 

We can offer showing the council members, as these guys are likely to be involved as this is a simple query we could add here.. makes sense?

**Comment by traumschule** [comment]
agree, thanks for boiling it down!

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/
wss://44.201.112.198.nip.io/ws-rpc

Members list removed
<img width="1440" alt="Снимок экрана 2022-11-08 в 18 31 28" src="https://user-images.githubusercontent.com/46903215/200622102-22818003-4bb4-44b1-be4e-fa69acd63a4c.png">
