### ISSUE TITLE
Profile page shows inconsistent number of digits

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3990]
[My Accounts](https://pioneerapp.xyz/#/profile) shows (transferable) balances with inconsistent decimals depending on amount.

Round to the same number of digits for each column.

**Comment by dmtrjsg** [comment]
@traumschule sorry we don't understand what you mean, is it possible to recreate such scenario using Alice account on playground?

Or point out what isn't as per your expectations based on the screenshot below:

<img width="1344" alt="Screenshot 2022-12-20 at 13 03 43" src="https://user-images.githubusercontent.com/93924525/208626995-82b0aaed-78f3-4879-8ef7-aa9cdf01ac87.png">

**Comment by traumschule** [comment]
Only visible with multiple accounts:
![decimals](https://user-images.githubusercontent.com/31551045/209767549-80f31e53-2aa2-44cd-bb1b-537af74222fd.png)

**Comment by chrlschwb** [comment]
I think the account balance is cut to two digits below zero. 
I think the display is correct.

**Comment by traumschule** [comment]
Sometimes the fraction is represented with 3 or less digits (even without in few cases) which disturbs the alignment when sorting by transferable.
The solution is easy: always show three-digit fractions.

**Comment by dmtrjsg** [comment]
@traumschule we always show just 2 digits for decimals. In your example the comma separated figures do not have decimals at all.

However we think the problem here lies in showing only 1 decimal and not two when the second one is 0. 

https://pioneer-2-storybook-joystream.vercel.app/?path=/story/common-tokenvalue--default&args=value:1+000+000+1000000000

So we suggest to address that instead.

Solution proposed would possible make it more confusing as decimals and comma separators would start to get mixed up.

**Comment by traumschule** [comment]
The problem was the inconsistency.

**Comment by dmtrjsg** [comment]
What do you mean by inconsistency @traumschule ?

**Comment by traumschule** [comment]
> We always display 2 decimals.

[Above screenshot](https://github.com/Joystream/pioneer/issues/3990#issuecomment-1366401722) shows sometimes we display 3 digits but it's ok ;)
