### ISSUE TITLE
Regression on WG `History` tab

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4034]
App crash on `/#/working-groups/storage`
```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'map')
    at useGroupActivities.ts:35:53
    at Object.So [as useMemo] (react-dom.production.min.js:168:377)
    at n.useMemo (react.production.min.js:23:113)
    at n.useGroupActivities (useGroupActivities.ts:21:22)
    at n.HistoryTabSidebar (HistoryTab.tsx:38:26)
```
Edit: only with https://dao-git-fork-mkbeefcake-fix-forumpostreplyntshow4022-joystream.vercel.app/#/working-groups/storage (#4023)

**Comment by traumschule** [comment]
Can't reproduce it on the official deployment currently.

**Comment by traumschule** [comment]
Happened again: https://pioneer-2-git-fork-chrlschwb-fix-4041-myrolesvalues-joystream.vercel.app/#/working-groups/builders

**Comment by IlyaSmiyukha** [comment]
I can replicate the issue as well. The backend doesn't return workerRewardAmountUpdatedEvents in the API call here. It is always undefined. And that's why the page crashes. See the screenshot below. I can't find Api documentation. To check is it stil needed.
<img width="1443" alt="Screenshot 2023-02-19 at 14 52 25" src="https://user-images.githubusercontent.com/39830587/219949412-203d2c4a-9a13-4a77-a8f3-261af78e3da3.png">

**Comment by chrlschwb** [comment]
@IlyaSmiyukha 
This is the query node for Joystream data.
https://query.joystream.org/graphql

**Comment by thesan** [comment]
@chrlschwb please don't close issues until they are merged in production (`main`)
