### ISSUE TITLE
Font text too small?

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#4094]
Perhaps I'm just getting old, but isn't the font text just needlessly small, despite being the main thing you want to process? Compare this
![Screenshot 2023-01-16 at 18 23 49](https://user-images.githubusercontent.com/437292/212736065-54a5bc33-2479-4985-a36c-173cba2bb88b.png)

to this

 
![Screenshot 2023-01-16 at 18 24 41](https://user-images.githubusercontent.com/437292/212736082-03f1a8ea-2449-4739-af90-f38357a86a5c.png)

isn't the latter way way easier to read, but also looks fine?

**Comment by traumschule** [comment]
A smart way UI to increase font size would be great (without having to resort to page zoom). Also the font isn't a most readable one.

**Comment by traumschule** [comment]
When writing forum posts I started to increase font size to `20px` via right-click 'inspect' on a line in the editor.
@bedeho try if that would be pleasant for you

![font-size](https://user-images.githubusercontent.com/31551045/215056176-00a1e693-9c36-413c-aac6-7cfb1d685f9b.png)

**Comment by bedeho** [comment]
Yeah, the fact that you were doing that is a pretty solid sign we should increase this 🤣

**Comment by thesan** [comment]
@bedeho @dmtrjsg @traumschule sorry I'm late on this but I'm not convinced increasing the font size is the right move.

It doesn't has to do with age as much as screen dpi getting denser with time, now there are even 4k laptop screens :open_mouth: .

However most websites don't increase there font sizes in reaction, e.g github, reddit, twitter all keep their text smaller than 16px (which is Pioneer's current default font size).

Instead Chrome matches the user's systems font scaling factor. I mainly use FF (mostly at 110% zoom but that's easy to adapt depending on the page) but when I open e.g: https://dao-git-fork-chrlschwb-fix-4094-fonttextsmall-joystream.vercel.app/#/forum/thread/324 on Chrome due to my system 120% font scaling factor I get `20px * 1.2` which looks bad IMO. I think this problem would affect most Chrome users and this is why most websites keep the same font sizes.

WDYT ?

**Comment by chrlschwb** [comment]
I think we should just add a font size controller. zoom in and zoom out...
https://github.com/Joystream/pioneer/issues/4308

**Comment by thesan** [comment]
> Also the font isn't a most readable one.

@traumschule the font color might be more of an issue than the font itself.
It's a grey which isn't very dark for a light theme reading font:
![image](https://user-images.githubusercontent.com/6571453/229080898-cc12d41c-716c-419a-8a08-5ec11a4a2c7e.png)

In contrast with the GH font color of this message (if you are using the "light default" theme):
![image](https://user-images.githubusercontent.com/6571453/229081280-f4865df3-b7ad-4941-8499-c4fc42081a95.png)

And it's not even the accessibility high contrast theme.

**Comment by traumschule** [comment]
Good point. Not sure if that's too hacky but we could use `onHover` `onActive` to switch to a high-contrast, bigger size etc scheme on post hover?
Or regarding the looking glass option:
> htmlElement.addEventListener('mousedown', focusPost)

**Comment by bedeho** [comment]
> sorry I'm late on this but I'm not convinced increasing the font size is the right move.

Yes you may very well be right that sizing is not the right fix, make the call.

> I think we should just add a font size controller. zoom in and zoom out...

I don't think this is wise. Products should just work and have good readability, adding tons of controls that users have to understand and manage should be the last resort, and not really warranted here.

**Comment by chrlschwb** [comment]
I will just try to change the font color then.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/thread/2
wss://54.205.24.16.nip.io/ws-rpc

Font color changed
<img width="227" alt="Screenshot 2023-04-27 at 19 06 16" src="https://user-images.githubusercontent.com/46903215/234921318-7d5974b7-3dd3-4e13-9b22-88b402f93d40.png">
<img width="1052" alt="Screenshot 2023-04-27 at 19 02 15" src="https://user-images.githubusercontent.com/46903215/234920726-c8781ccd-b6ef-470e-9b3d-215ec24bd419.png">
