### ISSUE TITLE
[USERSNAP] Cant unstake from My Profile

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4125]
**Taken at**: https://pioneerapp.xyz/#/election/past-votes
**Fields**:
- Houston, we have a problem.: Cant unstake from My Profile
- Comment: I managed to unstake my funds for voting in the last election successfully. Other keys do not show the unstake option, only the Show Election button. I managed to unstake only through Explorer or through Past votes.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/74f9830b-3fb2-411e-987e-8e70fc71b8bd-annotated_26a54ecc-20e9-4d5d-bfb2-de9bb8509fb3.png?etag=18fb794f4afc0918c2e0b83b99ac62a5)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/74f9830b-3fb2-411e-987e-8e70fc71b8bd-annotated_26a54ecc-20e9-4d5d-bfb2-de9bb8509fb3.png?etag=18fb794f4afc0918c2e0b83b99ac62a5)*

**Browser**: Yandex.Browser 23 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x726
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/481b511b-f45c-4c7a-a618-756529610970_screen_recording_e0ee8ed7-3b2d-40e8-b85c-e58b150ab053.webm?etag=7e09081252d70a46da5a26c84aa232c5)**
**[Open #383 in Usersnap](https://app.usersnap.com/l/feedback/945555bc-db84-44cd-b6a2-3539f80efd11?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Assigning high-prio label as all council-related tasks for the benefit of voters.

⚠️ In order to debug it properly, we need the exact flow on how to reproduce this issue.

**Comment by igrexac** [comment]
In short: My Profile incorrectly displayed information about the stake on some of my keys.
1. In the My Profile section, I successfully returned a stake for one of the candidates from one key.
2. When trying to unsteke from other keys, there was no unstake button. Instead, there was a Show Election button, which led to the previous elections (election #2, instead of #3), from which I had already restored the stake.
3. I managed to return the stake through the extrusion in the polkadot explorer
4. In the Election > Past votes section, there was also an unstake option.

**Comment by traumschule** [comment]
I checked with the author:
- the problem is with lock display on https://pioneerapp.xyz/#/profile
- the page showed information from the previous election
- it was possible to unlock the funds on https://pioneerapp.xyz/#/election/past-votes
