### ISSUE TITLE
[USERSNAP] Forum post auto-scrolling bug

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4129]
**Taken at**: https://pioneerapp.xyz/#/proposals/preview/81?post=69
**Fields**:
- Houston, we have a problem.: Forum post auto-scrolling bug
- Comment: When I follow a link to a specific post, like https://pioneerapp.xyz/#/proposals/preview/81?post=69, then if I try to scroll to another part of the page I will be auto scrolled back to the post after a few seceonds.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0f8b195b-3502-4893-9a24-4265c5e149be-annotated_8aff3c26-0b7f-4043-a40d-ddc523022ed8.png?etag=d102f9b1395b2f82df877f42c764d492)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0f8b195b-3502-4893-9a24-4265c5e149be-annotated_8aff3c26-0b7f-4043-a40d-ddc523022ed8.png?etag=d102f9b1395b2f82df877f42c764d492)*

**Browser**: Firefox 109 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1858x1171
**[Open #384 in Usersnap](https://app.usersnap.com/l/feedback/302c1b22-0355-47af-94c0-5ccbddfeb1c1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

## Technical guidance:

The `` is happening [here](https://github.com/Joystream/pioneer/blob/0d308b26de798e8d41b8a7680b18b395ec42f03e/packages/ui/src/forum/components/PostList/PostListItem.tsx#L71):
```ts
useEffect(() => {
  if (ref.current && isSelected) {
    ref.current.scrollIntoView({ behavior: 'smooth', inline: 'start' })
  }
}, [location, ref.current])
```
I'm not 100% sure which of the 2 `useEffect` dependencies is at fault but I don't think `ref.current` should be here.

**Comment by Honest0** [comment]
@chrlschwb   I would like to work on this issue. Hope you to assign me

**Comment by jokerjamal** [comment]
Based on the description, it appears that the auto-scrolling bug on the Pioneer forum is related to the following code snippet:
useEffect(() => {
  if (ref.current && isSelected) {
    ref.current.scrollIntoView({ behavior: 'smooth', inline: 'start' })
  }
}, [location, ref.current])

The issue seems to be that the code is scrolling to the selected post after a few seconds, even when the user is trying to scroll to another part of the page. One possible solution would be to remove ref.current as a dependency in the useEffect hook and only trigger the auto-scrolling behavior when isSelected changes:

useEffect(() => {
  if (isSelected) {
    ref.current.scrollIntoView({ behavior: 'smooth', inline: 'start' })
  }
}, [isSelected])

This way, the auto-scrolling behavior would only occur when a new post is selected, rather than constantly re-triggering every few seconds. This should resolve the issue of users being unable to scroll to other parts of the page without being auto-scrolled back to the selected post.

**Comment by traumschule** [comment]
@Honest0 any update, can you work with the above?

**Comment by polikosi** [comment]
Tested on: https://pioneer-2-git-fork-ilyasmiyukha-dev-joystream.vercel.app/#/proposals/preview/81?post=69

Now is working as expected. When I I follow a link to a specific post and scroll to another post, I will not be redirected to the previous post.
