### ISSUE TITLE
Allow users to provide alternative RPC and QN endpoints

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#4174]
![image](https://user-images.githubusercontent.com/6571453/218825154-57922750-73eb-4b9f-aa40-13d380f7af07.png)

**Comment by dmtrjsg** [comment]
Related to 
- #4108

**Comment by dmtrjsg** [comment]
⚠️ for experienced developer

**Comment by traumschule** [comment]
Please be specific how you want this implemented. As edit button next to the copy symbol which opens a modal or an input field somewhere?
4108 isn't related to QN selection, is it?

**Comment by dmtrjsg** [comment]
@traumschule @chrlschwb 

We added the link to 4108 due to QN wasn't stable and it was triggering this error described in 4108 more often. 

Re implementation, let's add a "Custom" option to the drop down

<img width="918" alt="Screenshot 2023-03-29 at 12 04 19" src="https://user-images.githubusercontent.com/93924525/228467970-9654da4d-6732-473b-b817-d2174b0ee36d.png">


And when selected all endpoints can be provided as custom URLs:

RPC
QN
Faucet
Backend

**Comment by traumschule** [comment]
Early design stage :)
![custom](https://user-images.githubusercontent.com/31551045/228613351-5a52680d-9ef7-4a7d-aedf-507cca5dd34d.png)
