### ISSUE TITLE
LInk to Calamar from Block links in the app

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4397]
We have a few places in the app where a particular block links to polkadot. Suggestion to swap this to Calamar explorer instead.

![Screenshot 2023-05-30 at 12.12.48.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/86185883-c0d3-47bd-95f6-011a4b959bca)

**Comment by dmtrjsg** [comment]
Let's add this option to the settings @thesan ? :)

**Comment by bedeho** [comment]
You can't  add this to setings in any convenient way, because the schema for how to access different resources: blocks, accountss, transctions, etc., it entirely depends on the service type, not the specific host. So if one day Calamar did not exist, and Subscan was going to be used, the urls for accessing different type resources would likely be different.

**Comment by thesan** [comment]
Calamar seems to still have some rough edges like [not showing event parameters](https://discord.com/channels/811216481340751934/1035125653722365993/1113738326512521246), also https://github.com/Joystream/pioneer/pull/4401#pullrequestreview-1454987995. So even though I had suggested this, now I think we should probably keep the Polkadot app for block links for now.

**Comment by dmtrjsg** [comment]
Calamar is great if you don't know the block number, due to good search.. but if you know the block number - Polkadot app has more information on it. So this issue does not make sense to ship as of yet. Adding to Icebox before more info appears on Calamar for known blocks.
