### ISSUE TITLE
Pioneer: long page load time/unresponsiveness

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4503]
Some users (myself included) are reporting very long load times for the forums (other pages take long times too but forum is the most used area for now so is most noticeable). The page seems to load fine but the actual content (presumably from the QN) is having trouble loading and sometimes requires refreshing a few times.

Is it possible the QN infrastructure is getting overwhelmed?

Quick Discord poll on it: https://discord.com/channels/811216481340751934/812343711870091285/1141445546922479746

**Comment by traumschule** [comment]
Worth checking for (too) rich queries.

**Comment by thesan** [comment]
@traumschule 
> Worth checking for (too) rich queries.

Yes some queries might be too big. IMO though we should first tackle the queries which are resent multiple times like on the forum: #4484 and #4485 because these are definitely unnecessary and are putting a huge load on the QN.

OTOH safely removing individual fields from queries will take more time because many queries are reused in multiple places and removing a field which is useless on most components calling a given query and/or most user state would create bugs/crashes for particular cases. So this untangling work will be hard. That said it should definitely be done too.

**Comment by mochet** [comment]
I would say this has now been resolved but not sure if I should close the issue just yet
