### ISSUE TITLE
Independent Resource Identifiers

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#50]
Lets say you are writing a blog post or.a text for an opening, and you would like to reference a specific proposal, say proposal with id 789. One way to do that is to put a hard link into the text where you give a full link like this http://www.somejoystreamsite.com/proposals/id/789, for example. The problem with this is that if someone is reading your content through another app for joystream, then rather than getting linked to the proposal, they get sent to another site, and iin the future `somejoystreamsite.com` may not even exist. This is not only about proposals, but really any resource in the system, like 

- a block
- a transaction
- a member
- a blog thread
- a blog post
- a proposal
- a proposal discussion entry
- an opening
- an application
... and probably many more.

We need a standard for how to encode references to such resources in texts for the Joystream blockchain. This will require more sophisticated composer and rendering experience for such text fields where we currently just have a generic markdown editor.

**Comment by jodator** [comment]
If I understand that issue correctly, the problem is

1.  How to represent this link in markdown
2.  How to represent this link in App
3.  How to represent this link during the content editing

Ad. 1. :

It may be something similar to a link markup:

```markdown
@proposal["Proposal title"](http://www.somejoystreamsite.com/proposals/id/789)
or
@proposal["Proposal title"](789)
```

Ad. 2.: 

This would require a markdown to HTML processor in the Joystream App that will detect such markup and potentially display a rich widget or in-app link to a proposal. AFAIR most of the Markdown processors allow custom extensions.

Ad. 3.:

The editor can detect this link and represent it internally as special objects. This can be also displayed as a "widget", so offering a rich preview. An example of this might be [this demo](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/using-react-in-a-widget.html#demo). It renders a widget containing a React component inside the editing area.

**Comment by bedeho** [comment]
Very interesting, that editor looks like a promising alternative then indeed. I assume its possible to restyle easily also?

**Comment by jodator** [comment]
Shouldn't be a problem – there's a [theming guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html) for the UI and the [content inside the editor can be styled](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html) as well. Additionally, one can use [own UI to control the editor](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/external-ui.html), but that's overkill IMO.

**Comment by bedeho** [comment]
Superseded by https://github.com/Joystream/pioneer/issues/1091
