### ISSUE TITLE
Check queries performance

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#769]
I think that some..

**Comment by p-sad** [comment]
### Before vs after:
getWorkingGroups query
![image](https://user-images.githubusercontent.com/21345040/121503894-c8e1d500-c9e1-11eb-8bd6-bc93c075a301.png)
![image](https://user-images.githubusercontent.com/21345040/121503966-dd25d200-c9e1-11eb-9198-2e52b2666d64.png)

getWorkingGroupsConnectionQuery
![image](https://user-images.githubusercontent.com/21345040/121503770-ab147000-c9e1-11eb-9596-612ad05d1d42.png)
![image](https://user-images.githubusercontent.com/21345040/121504123-03e40880-c9e2-11eb-886c-c7306f664b33.png)

getWorkersQuery
![image](https://user-images.githubusercontent.com/21345040/121504313-355cd400-c9e2-11eb-86e5-964c2df21129.png)
![image](https://user-images.githubusercontent.com/21345040/121504399-460d4a00-c9e2-11eb-8bc6-7679d3110462.png)

The workers query still takes a bit long; it might be worth it to include only some member fields per worker instead of all of them.

**Comment by jodator** [comment]
Thanks! Nice summary :)
