### ISSUE TITLE
Add Proposal: Amend Constitution

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#876]
@[figma](https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=265%3A19450)

Handle proposal's specific parameters:

- [ ] New constitution upload field

See notes in #806.

⚠️ Diff in RTFs? How to fetch and display?

Without it the issue is a 2.

**Comment by stepien4soft** [comment]
What kind of field should we create there? On the figma design there should be dropzone (https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=265:19450). On the other hand, the api expects text there.
For now the easiest way to implement this proposal is set this field as a text input. Let me know what do you think

**Comment by jodator** [comment]
> For now the easiest way to implement this proposal is set this field as a text input. Let me know what do you think

@bedeho & @stepien4soft For now I'd propose a markdown input:

![](https://user-images.githubusercontent.com/247363/144813840-78be0c66-b0a3-40ed-ad39-44c057784f69.png)

**Comment by bedeho** [comment]
The constitution is effectively a very large text document, hence, its very implausible that someone is going to be editing it directly in Pioneer. More likely, they would take the existing constitutional text, edit it using some other software, and then want to make a proposal out of this finished text, which likely would be a file. So what would be useful would indeed be to allow just a dropzone for a file, but additionally, what could be useful would be to show a Diff to the user before the proposal submission happens, so that they can be sure they are picking the correct file. This diff viewer should probably also just have an effort kind of state if the selected file is not a valid Markdown file, e.g. if they picked something random, like a video or mp3 or something. If doing these extra steps requires additional help from a designer, then please make issues describing this, and add this work to the backlog, we should not block completing some  MVP version of this proposal in order to get all of this extra functionality I am describing here.

Hope that helps.

**Comment by traumschule** [comment]
Closing this according to https://github.com/Joystream/pioneer/issues/4390#issuecomment-1558535152
