### ISSUE TITLE
External link support for tooltips

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#888]
Currently tooltips external `tooltipLinkURL` are not accessible because `<Tooltip />` always renders a react-router `<Link />`.

Fixing this would also remove the need to use `<MemoryRouter />` in stories with an external `tooltipLinkURL`

**Comment by oleksanderkorn** [comment]
Proposed solution: 
If link starts with `/` or `#` using the React Router Link, otherwise use `styled.a`:
![image](https://user-images.githubusercontent.com/9252017/142502834-2b0ccfdd-caf2-4625-82a3-ea6dff1d96a8.png)

Example:
![image](https://user-images.githubusercontent.com/9252017/142502644-0cef7d6c-718b-43fd-9529-2b5335ec9ef1.png)
